### ISSUE TITLE
Hidden constraint: alex >= 2.3.5

### ISSUE THREAD

**Issue by copton** [haskell/haskell-platform#11]
Hi

apparently, alex bootstraps itself via alex. According to [1], older versions of alex used to generate code with bang patterns but leave the corresponding module without a 'LANGUAGE BangPatterns' pragma.

Consequently, building Haskell Platform 2012.2.0.0 or 2012.4.0.0 with, for instance, alex 2.3.3, fails: 
---8<---
dist/build/alex/alex-tmp/Scanner.hs:294:18:
    Illegal bang-pattern (use -XBangPatterns):
    ! (base)
-->8---

Building with alex 3.0.1, for instance, works.

I don't know exactly, which one is the threshold version for this, but according to [1] it is version 2.3.5.

Maybe this constraint should be checked by the configure script or at least be documented somewhere.

I hope, I didn't miss anything obvious.

Greetings,

Alex

[1] http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=635113

**Comment by gbaz** [comment]
I think the hermeneutic new-builds are fixing this?
