### ISSUE TITLE
Making haskell-platform less intrusive on OS X

### ISSUE THREAD

**Issue by jrp2014** [haskell/haskell-platform#125]
Currently, so far as I can tell, haskell-platform for OS X uses frameworks or plants files in /usr/local, which requires the use of sudo and / or makes it hard to uninstall reliably.

This is not inevitable.  ghcformacosx (https://github.com/ghcformacosx/ghc-dot-app) does a great job of putting ghc into a single .app folder that can trashed, leaving no trace other, perhaps, than a modification to the path in ~/.profile and any ~/.cabal and other package files.

What are the plans for making the new haskell-plaform less intrusive than the old?

**Comment by gbaz** [comment]
closing because this appears to have been a question and a localized issue?
