### ISSUE TITLE
Issue with hashable in 2014.2RC2 on MacOS 10.6

### ISSUE THREAD

**Issue by bovinespirit** [haskell/haskell-platform#130]
When I tried to cabal install profunctors on a fresh install of platform 2014.2rc2 I got this error:

Loading package text-1.1.0.0 ... linking ... done.
Loading package hashable-1.2.2.0 ... <command line>: can't load .so/.DLL for: /Library/Haskell/ghc-7.8.3-x86_64/lib/hashable-1.2.2.0/libHShashable-1.2.2.0-ghc7.8.3.dylib (dlopen(/Library/Haskell/ghc-7.8.3-x86_64/lib/hashable-1.2.2.0/libHShashable-1.2.2.0-ghc7.8.3.dylib, 9): Library not loaded: @rpath/libHStext-1.1.0.0-ghc7.8.3.dylib
  Referenced from: /Library/Haskell/ghc-7.8.3-x86_64/lib/hashable-1.2.2.0/libHShashable-1.2.2.0-ghc7.8.3.dylib
  Reason: image not found)

Forcing an install of hashable then installing new versions of unordered-containers and case-insensitive solved it.  The same problem seems to affect vector as well.

**Comment by gbaz** [comment]
closing as obsolete I guess...
