### ISSUE TITLE
failure of symLinkInto, if not exists $prefix/share/man/man1

### ISSUE THREAD

**Issue by watiko** [haskell/haskell-platform#133]
Default ubuntu 14.04 does not have /usr/local/share/man/man1 directory.
So activate-hs fails in that line (hptool/os-extras/posix/bin/activate-hs) :

```sh
symLinkInto "$ghcRoot"/share/man/man1/* "$prefix/share/man/man1"
```

Definition of symLinkInto:

```sh
symLinkInto() {
    run ln -sf "$@"
}
```

**Comment by mzero** [comment]
fixed in master
