### ISSUE TITLE
'cabal install' fails with fresh install of 2014.2.0.0 for Windows, 64bit

### ISSUE THREAD

**Issue by vesten** [haskell/haskell-platform#139]
Running the installer for 2014.2.0.0 and accepting all defaults on a Windows Vista Enterprise SP2 (work machine, not my fault) machine, then 'cabal update', then 'cabal install cabal-install' results in:

```
>cabal install cabal-install
  Resolving dependencies...
  Configuring cabal-install-1.20.0.3...
  Failed to install cabal-install-1.20.0.3
  Last 10 lines of the build log ( C:\Users\... ):
  Configuring cabal-install-1.20.0.3...
  setup-Cabal-1.18.1.3-x86_64-windows-ghc-7.8.3.exe: does not exist
  cabal: Error: some packages failed to install:
  cabal-install-1.20.0.3 failed during the configure step. The exception was:
  ExitFailure 1
```

However,
    ...\AppData\Roaming\cabal\setup-exe-cache\setup-Cabal-1.18.1.3-x86_64-windows-ghc-7.8.3.exe exists.

Also, uninstalling 64bit and similarly installing 32bit 2014.2.0.0 does not exhibit this problem.

**Comment by mac10688** [comment]
While researching this issue this page kept coming up for me so I'll document my solution for future searchers. I had another gcc in  the path (\Programming\IDEs\GnatStudio\bin;) that it was hitting. I guess it was the wrong kind of gcc and something was failing. I removed that from the environment path and everything started working.

To find the issue I had to use - v3 as mentioned above but also, unless I overlooked something, had to clear my tempdata. Then the message was more clear.

**Comment by pawelsawicz** [comment]
Had same issue.

I was having Cabal 1.18.x then I updated it by ```cabal install cabal-install --global``` and it is working now.
Problem occurred, when I was trying to ```cabal install alex happy yesod-bin``` via http://www.yesodweb.com/page/quickstart

**Comment by CThuleHansen** [comment]
I am having this issue, how do I solve it for win64?

**Comment by randen** [comment]
CThuleHansen, there seem to be a couple of problems tangled in this one issue, so it is not clear to me which problem here you might be having.  Could you review the various problems above and see which one it is that you are having, and possibly try some of the noted work-arounds mentioned in this issue, or please submit a new issue if you are having a problem that sounds like the title of this issue but has different details.

**Comment by CThuleHansen** [comment]
I downloaded the minimalist ghc and newest cabal.. so kind of abandoned it

**Comment by dom96** [comment]
Same problem here.

**Comment by emilbaek** [comment]
Had the same problem. Look if you have gcc installation in your path other than the one that comes with Haskell in my case it was mingw.

**Comment by doctorme** [comment]
Thanks @emilbaek !

**Comment by 23Skidoo** [comment]
> Look if you have gcc installation in your path other than the one that comes with Haskell in my case it was mingw.

This should be fixed in latest `cabal-install` (and therefore, latest HP).
