### ISSUE TITLE
Incorrect path to activate-hs in instructions

### ISSUE THREAD

**Issue by ilkka** [haskell/haskell-platform#148]
The [instructions for the Generic Linux Haskell Platform](http://www.haskell.org/platform/linux.html) have a typo in the path to activate-hs: there should be an underscore in `x86_64`, so the last line should read

```
sudo /usr/local/haskell/ghc-7.8.3-x86_64/bin/activate-hs
```

**Comment by mzero** [comment]
no longer relevant - we now have a linux installer script and the instructions reference that
