### ISSUE TITLE
Incorrectly ordered PATH entries on Windows

### ISSUE THREAD

**Issue by 3noch** [haskell/haskell-platform#152]
After installing the Haskell Platform, if you run `cabal install cabal-install`, you will still end up using the old version. That's because the System and user PATH variables are set up in such a way that the old version of cabal shadows the new one. AFAIK, Windows non-intuitively respects entries on the system PATH over the user-level PATH (the user path is appended to the system one). It also respects the first match as opposed to the last (opposite of Linux).

**Comment by gbaz** [comment]
Closing as dup of  #51
