### ISSUE TITLE
Pass --hoogle to haddock when building documentation

### ISSUE THREAD

**Issue by dato** [haskell/haskell-platform#157]
Hello!

Would it be possible to pass `--hoogle` to haddock when building documentation?

This would make it possible (with some gluing work) for a local instance of Hoogle to search/index packages provided by the platform.

Note that the GHC docs themselves already provide hoogle index files.

Thanks for considering!

**Comment by mzero** [comment]
this sounds like fun. Adding the --hoogle shouldn't be a big deal, I don't think...
... can you provide the gluing recipe?

**Comment by dato** [comment]
Cool, thanks. As for the glue:

- Passing _--hoogle_ to haddock makes it output a _&lt;pkg>.txt_ file for each package, in addition to HTML.
- This _&lt;pkg>.txt_ file can be converted to Hoogle’s binary format with `hoogle convert` (resulting in  _&lt;pkg>.hoo_).
- All _&lt;pkg>.hoo_ files can be combined into a single _default.hoo_ file with `hoogle combine`.
- You can place this _default.hoo_ file in a given directory _&lt;DIR>_, and serve it locally with `hoogle server --local --databases <DIR>`.

Note that I’m only posting the above as a reference. I’m not sure that Haskell Platform should implement it beyond providing the _&lt;pkg>.txt_ files.

This is because the process should be implemented in a fashion so as to automatically update as new packages get installed, i.e., possibly out of cabal.

Then this process could integrate Haskell Platform docs, the same way it can integrate GHC docs today from `/usr/share/doc/ghc/html/libraries/*/*.txt`.

Thanks!
