### ISSUE TITLE
activate-hs creates broken symlinks on Linux

### ISSUE THREAD

**Issue by jarthurgross** [haskell/haskell-platform#158]
I just followed the instructions [here](https://www.haskell.org/platform/linux.html#binary) for installing the linux binary (I'm running Linux Mint 17). After running `activate-hs` as described, I was surprised that tab-autocomplete didn't recognize any of the haskell commands (*e.g.* `ghc`). After exploring a bit, it turned out all the symlinks created in `/usr/local/bin` were missing the leading `/` (*e.g.* `ghc -> usr/local/haskell/ghc-7.8.3-x86_64/bin/ghc` instead of `ghc -> /usr/local/haskell/ghc-7.8.3-x86_64/bin/ghc`).

**Comment by mzero** [comment]
fixed in master branch now

**Comment by mzero** [comment]
Seems like it works in the current release candidate:

    $ ls -l /usr/local/bin/ghc
    lrwxrwxrwx 1 root staff 53 Jul  3 18:50 /usr/local/bin/ghc -> /usr/local/haskell/ghc-7.10.1.20150630-x86_64/bin/ghc

Did you do something like:

    cd /usr/local/haskell/ghc-7.10.1.20150630-x86_64/bin
    ./activate-hs

That should work, too, but it takes a different pathway... Wondering if this has anything to do with Min specifically.

**Comment by mzero** [comment]
I believe this is now fixed. Can anyone with Linux Mint verify?
