### ISSUE TITLE
Why ghc-7.8.3-x86_64 must should put to the path "/usr/local/haskell"?

### ISSUE THREAD

**Issue by joostshao** [haskell/haskell-platform#159]
when there is no "/usr/local/haskell", i "./ghci", it failed.
there must be a haskell binary in "/usr/local/haskell".

why ?

**Comment by mzero** [comment]
I'm not sure what you are asking. Is it:

* Why wasn't `/usr/local/haskell/bin` put on the path?
* Why didn't `./ghci` run?
* Why does it put things in `/usr/local/haskell/`?

For reference, the `activate-hs` script puts symlinks to all the binaries into `/usr/local/bin`
