### ISSUE TITLE
Misleading links on http://trac.haskell.org/haskell-platform

### ISSUE THREAD

**Issue by nomeata** [haskell/haskell-platform#16]
Hi,

http://trac.haskell.org/haskell-platform still exists and points to the darcs repo, which is (AFAIK) not used any more. That page needs some cleanup.

Greetings,
Joachim

**Comment by gbaz** [comment]
at least we're not linking to it anymore..

**Comment by gbaz** [comment]
looks like trac points to github now. We could make it even clearer, but I think this suffices?
