### ISSUE TITLE
Don't use novelty fonts in documentation

### ISSUE THREAD

**Issue by ikirill** [haskell/haskell-platform#160]
The headings font on OSX, as seen in this file:

https://github.com/haskell/haskell-platform/blob/master/hptool/os-extras/osx/doc/start.html.mu#L19

is Skia, which is a novelty font (a font aimed to showing off instead of being clean and readable). According to https://www.myfonts.com/fonts/apple/skia/, it was a showcase for Apple's technology at some point.

It is generally considered (e.g., http://practicaltypography.com/goofy-fonts.html) that font choices, even if you want them to stand out, should not be novelty or goofy fonts.

Would it be possible to change the font settings? Remove Skia from the font-display value? Perhaps even just use the default font, as it is likely to be already configured to something reasonable?

**Comment by mzero** [comment]
Could I poke you ( @ikirill  ) to send me a pull request with a fix?
