### ISSUE TITLE
Incorrect path to activate-hs script in Haskell Platform Linux Generic Binaries instructions

### ISSUE THREAD

**Issue by mnemonicflow** [haskell/haskell-platform#162]
On the page https://www.haskell.org/platform/linux.html , section Generic Linux Binaries, the path to the activate-hs bash script is incorrect, it has a dash between 'x86-64' instead of an underscore i.e. ''x86_64" like the name of the downloaded archive: haskell-platform-2014.2.0.0-unknown-linux-x86_64.tar.gz

The absolute file path should be: **/usr/local/haskell/ghc-7.8.3-x86_64/bin/activate-hs**

**Comment by safinaskar** [comment]
Hi. I still see this typo on the site. Please, just fix it. Why this is so difficult?

**Comment by mzero** [comment]
will be fixed in the next release and web site update - within the month.
why is it hard... oy - because we don't have anyone in charage of the HP website, and updating the site involves an arcane process....

**Comment by mzero** [comment]
no longer relevant - we now have a linux installer script and the instructions reference that
