### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by malloc82** [haskell/haskell-platform#164]
I got the following error while installing haskell-platform 2014.2.0.0:

```
[23 of 28] Compiling OS.Win           ( src/OS/Win.hs, dist/build/hptool/hptool-tmp/OS/Win.o )

src/OS/Win.hs:78:48:
    Ambiguous occurrence ‘C.installedPackageId’
    It could refer to either ‘C.installedPackageId’,
                             imported qualified from ‘Distribution.InstalledPackageInfo’ at src/OS/Win.hs:14:1-55
                          or ‘C.installedPackageId’,
                             imported qualified from ‘Distribution.Package’ at src/OS/Win.hs:15:1-42
```
It's referring to this: 
https://github.com/haskell/haskell-platform/blob/master/hptool/src/OS/Win.hs#L14-L15
Both as C? Is that a bug?

**Comment by malloc82** [comment]
It does work after getting line 14 commented out. Maybe getting 15 commented out will work too.

**Comment by randen** [comment]
When committed, this file was built against Cabal 1.18.1.3.  Since then, Distribution.Package has been modified and in more recent versions of the Cabal library, it now exports installedPackageId (in the class PackageInstalled), which is the breakage you have found.  If building the hptool against a more recent Cabal library, there may be other things that are broken as well.

**Comment by egarrulo** [comment]
I am experiencing a similar problem.  What `cabal-install` version is recommended along with Cabal 1.18.1.3 (with GHC 7.10.1)?  Is there a way to wipe out my current Cabal installation to start afresh? Thank you.

**Comment by mzero** [comment]
The change in Cabal happened in 1.22.0. Any version of Cabal prior to that should be fine.... 

BUT - the pre-release branch now has the (simple) fix for this. You can (should) pull that branch and build that.

If you want to make the patch yourself, just surround line 14 like so:

    #if !MIN_VERSION_Cabal(1,22,0)
    import qualified Distribution.InstalledPackageInfo as C
    #endif

And add `CPP` to the LANGUAGE pragma on line 1:

     {-# LANGUAGE CPP, RecordWildCards, OverloadedStrings #-}

**Comment by egarrulo** [comment]
Thank you, but the fix doesn't work.

Maybe the cause of the error that I am experiencing is different.  Here it is the build that fails:

    ***
    *** Building hptool
    ***
    Package has never been configured. Configuring with default flags. If this
    fails, please run configure manually.
    Resolving dependencies...
    Configuring hptool-0.1...
    Building hptool-0.1...
    Preprocessing executable 'hptool' for hptool-0.1...
    [ 1 of 28] Compiling OS.Win.WinUtils  ( src/OS/Win/WinUtils.hs, dist/build/hptool/hptool-tmp/OS/Win/WinUtils.o )

    src/OS/Win/WinUtils.hs:10:1: Warning:
        The import of ‘<$>’ from module ‘Control.Applicative’ is redundant
    [ 2 of 28] Compiling Utils            ( src/Utils.hs, dist/build/hptool/hptool-tmp/Utils.o )
    [ 3 of 28] Compiling Types            ( src/Types.hs, dist/build/hptool/hptool-tmp/Types.o )

    src/Types.hs:19:1: Warning:
        The import of ‘Control.Applicative’ is redundant
          except perhaps to import instances from ‘Control.Applicative’
        To import instances alone, use: import Control.Applicative()
    [ 4 of 28] Compiling PlatformDB       ( src/PlatformDB.hs, dist/build/hptool/hptool-tmp/PlatformDB.o )
    [ 5 of 28] Compiling Releases2012     ( src/Releases2012.hs, dist/build/hptool/hptool-tmp/Releases2012.o )
    [ 6 of 28] Compiling Releases2013     ( src/Releases2013.hs, dist/build/hptool/hptool-tmp/Releases2013.o )
    [ 7 of 28] Compiling Releases2014     ( src/Releases2014.hs, dist/build/hptool/hptool-tmp/Releases2014.o )
    [ 8 of 28] Compiling Releases         ( src/Releases.hs, dist/build/hptool/hptool-tmp/Releases.o )
    [ 9 of 28] Compiling Paths            ( src/Paths.hs, dist/build/hptool/hptool-tmp/Paths.o )
    [10 of 28] Compiling OS.Win.WinPaths  ( src/OS/Win/WinPaths.hs, dist/build/hptool/hptool-tmp/OS/Win/WinPaths.o )
    [11 of 28] Compiling Dirs             ( src/Dirs.hs, dist/build/hptool/hptool-tmp/Dirs.o )

    src/Dirs.hs:20:15:
        Ambiguous occurrence ‘*>’
        It could refer to either ‘Prelude.*>’,
                                 imported from ‘Prelude’ at src/Dirs.hs:1:8-11
                                 (and originally defined in ‘GHC.Base’)
                              or ‘Development.Shake.*>’,
                                 imported from ‘Development.Shake’ at src/Dirs.hs:5:1-24

    src/Dirs.hs:87:13:
        Ambiguous occurrence ‘*>’
        It could refer to either ‘Prelude.*>’,
                                 imported from ‘Prelude’ at src/Dirs.hs:1:8-11
                                 (and originally defined in ‘GHC.Base’)
                              or ‘Development.Shake.*>’,
                                 imported from ‘Development.Shake’ at src/Dirs.hs:5:1-24

**Comment by mzero** [comment]
Ah, /that/ error. That is due to the changes to Prelude in 7.10. A lot of packages are going to have this or similar, so get used to seeing it!

Any how the fix is easy... Please build from the pre-release branch, where this issue has been fixed too.
