### ISSUE TITLE
C2HS requires newer version gcc

### ISSUE THREAD

**Issue by deech** [haskell/haskell-platform#166]
Hi all,
I'm having an unfortunate issue on Windows where C2HS seems to require a newer version of `gcc` (4.8.x) than what is shipped with the newest Haskell Platform (4.6.x). The original issue was posted to haskell-cafe here: https://mail.haskell.org/pipermail/haskell-cafe/2015-March/118474.html

I tried simply replacing the `mingw` folder in Haskell Platform directory with the one that contains the newer `gcc` binaries however this leads to linking errors because GHC itself it built with 4.6.*.

I tried working with the newer MinGHC install but that has similar issues with respect to the `gcc` version.

I realize this is a Cabal issue since what I really need is to be able to instruct Cabal to use the newer version of `gcc` for the `c2hs` phase of build and switch back to the default for compiling, but I was wondering if anyone here can suggest a work-around since this is really only an issue on Windows.

Thanks!

**Comment by randen** [comment]
The gcc comes along with GHC, so it is GHC itself which determines the gcc version.  Perhaps you meant to submit this to the c2hs github issues list?

**Comment by deech** [comment]
Talking it over with the maintainer, I'm not sure this is a `c2hs` problem. The central problem is not being able to pick a version of `gcc` just for the preprocessing phase of the build step. I had just hoped that someone here had run into this on Windows before and had come up with a work-around.

**Comment by thomie** [comment]
This will be fixed in ghc-8, or perhaps ghc-7.10.3 if that ships. See http://ghc.haskell.org/trac/ghc/ticket/10726.

**Comment by gbaz** [comment]
Closing, as anything platform specific seems to be resolved with regards to this...
