### ISSUE TITLE
'ghci' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by uh0h** [haskell/haskell-platform#167]
When typing ghci into command prompt I get the above message.  Any help? Thanks.

**Comment by randen** [comment]
This is the message which the Windows OS command prompt will display if it cannot find the named command as either a built-in or as a program/batch file on the current PATH.

Check your PATH variable from that command prompt ("echo %PATH%") as it sounds like the Haskell Platform install location is in the PATH environment variable.  You should see, somewhere near the very start of the output from "echo %PATH%", something like "C:\Program Files\Haskell Platform\2014.2.0.0\bin".

Note that if you have just installed the Haskell Platform, any already-opened command prompt windows will not reflect the updated PATH, so you might just need to launch a new Command Prompt (cmd.exe) and you'll then get the updated PATH.

If still no luck, perhaps something has happened to the actual install directory, so also check that (depending on the version of the Haskell Platform which is installed, the version number will be different) "C:\Program Files\Haskell Platform\2014.2.0.0\bin\ghci.exe" does exist.

**Comment by gbaz** [comment]
closing as it appears to be a localized issue?

**Comment by trytensorflow** [comment]
> If still no luck, perhaps something has happened to the actual install directory, so also check that (depending on the version of the Haskell Platform which is installed, the version number will be different) "C:\Program Files\Haskell Platform\2014.2.0.0\bin\ghci.exe" does exist.

C:\Program Files\Haskell Platform does not exist on my Computer although the installation was successful. How can I get the location?

**Comment by ads3g20** [comment]
> 

Did you ever figure this out? I'm having the same problem
