### ISSUE TITLE
just installed, but WinGHCi dies immediately

### ISSUE THREAD

**Issue by Brrrknee** [haskell/haskell-platform#170]
Win8.1Pro, 64b OS
just downloaded most recent (7.8.3) and installed; the cmdline interface starts a cmd window and a prompt "prelude>"... but I want to work via the window gui, however it fails.
WinGHCi window opens, then an error dialog kills the process:
![winghci immediate fatal error](https://cloud.githubusercontent.com/assets/11205856/6884019/9249cef8-d59b-11e4-8aa4-75645f948278.PNG)
I had used all defaults in the install.  Nothing unique.

**Comment by randen** [comment]
Possibly related: #52

**Comment by gbaz** [comment]
Appears fixed with 7.10.3?
