### ISSUE TITLE
Broken package cgi-3001.2.2.1 on Haskell Platform 2015.2.0.0 alpha 2 64bit.pkg

### ISSUE THREAD

**Issue by BeeJay71** [haskell/haskell-platform#171]
After a fresh HP 2015.2.0.0 install on Mac OS X "ghc-pkg check" on the console gives this output:

'There are problems in package cgi-3001.2.2.1:
  dependency "mtl-2.2.1-9d6d3937c3a89aa7f29852ba03f9c592" doesn't exist
  dependency "network-uri-2.6.0.1-8c523f0a13f0f03c68f10e0359bde85e" doesn't exist

The following packages are broken, either because they have a problem
listed above, or because they depend on a broken package.'

With "sudo ghc-pkg unregister cgi" and "cabal install cgi" I could temporarely fix it.

**Comment by mzero** [comment]
It is working in the latest alpha 3 build.
By any chance had you installed a non-platform version of GHC at some point?

**Comment by mzero** [comment]
still all okay in 7.10.2 RC1 on clean Mac install. Marking done
