### ISSUE TITLE
hptools/src/GhcDist.hs does not compile

### ISSUE THREAD

**Issue by mjfh** [haskell/haskell-platform#173]
I tried to compile haskell-platform from scratch with ghc 7.8.3 as well as 7.10.1. In either case it fails at GhcDist.hs with the error message

<pre>
Building hptool-0.1...
Preprocessing executable 'hptool' for hptool-0.1...
[29 of 30] Compiling GhcDist          ( src/GhcDist.hs, dist/build/hptool/hptool-tmp/GhcDist.o )

src/GhcDist.hs:104:38:
    No instance for (CmdString t0) arising from a use of ‘command’
    The type variable ‘t0’ is ambiguous
    Note: there are several potential instances:
      instance CmdString Data.ByteString.Internal.ByteString
        -- Defined in ‘Development.Shake.Command’
      instance CmdString Data.ByteString.Lazy.Internal.ByteString
        -- Defined in ‘Development.Shake.Command’
      instance CmdString () -- Defined in ‘Development.Shake.Command’
      ...plus one other
    In a stmt of a 'do' block:
      (Stdout cppVersion, Stderr _) &lt;- command
                                         [] cppCommand ["--version"]
    In the expression:
      do { let cppCommand
                 = fromMaybe
                     (error $ "Haskell CPP command not found in " ++ settingsFile)
                     (lookup "Haskell CPP command" settings);
           (Stdout cppVersion, Stderr _) &lt;- command
                                              [] cppCommand ["--version"];
           return . listToMaybe
           $ filter
               ((`isInfixOf` cppVersion) . cppCommandName)
               [minBound .. maxBound] }
    In an equation for ‘getCppCommand’:
        getCppCommand settings settingsFile
          = do { let cppCommand = ...;
                 (Stdout cppVersion, Stderr _) &lt;- command
                                                    [] cppCommand ["--version"];
                 return . listToMaybe
                 $ filter
                     ((`isInfixOf` cppVersion) . cppCommandName)
                     [minBound .. maxBound] }
</pre>

Have you any idea how to fix it?
Jordan

**Comment by lemoce** [comment]
I had same problem on GHC 7.8.4. I tried also run cabal install from the platform source root, but I got also an error:


    Configuring haskell-platform-2014.2.0.0...
    Failed to install haskell-platform-2014.2.0.0
    Build log ( /home/27190057897/.cabal/logs/haskell-platform-2014.2.0.0.log ):
    cabal: Error: some packages failed to install:
    haskell-platform-2014.2.0.0 failed during the configure step. The exception
    was:
    user error (Using 'build-type: Custom' but there is no Setup.hs or Setup.lhs
    script.)

The log file was empty.

**Comment by spakin** [comment]
I was able to fix this by changing the `shake` build dependency in `hptool/hptool.cabal` to `shake < 0.15`.  I submitted pull request #174 with that modification.

**Comment by eburgueno** [comment]
Hello, I can confirm that #174 works and haskell-platform now compiles ok, but only when the patch is applied to this repo, not the tarball download from the [main](https://www.haskell.org/platform/linux.html) page. Thanks @spakin.

**Comment by mjfh** [comment]
Thanks, I'll give it a try.
j
