### ISSUE TITLE
OS X & 2015 alpha 2: wrong GHC search path?

### ISSUE THREAD

**Issue by notcome** [haskell/haskell-platform#175]
I am trying to build Haskell Platform 2015.2.0.0 Alpha 2. I doubt that something went wrong with GHC's search path. For example, I tried to import Data.Text in GHCi:

```
Prelude> import Data.Text
*** Parser:

<no location info>:
    Could not find module ‘Data.Text’
    Perhaps you haven't installed the "dyn" libraries for package ‘text-1.2.0.4@text_IINWRW1LxFGIctooOLjJAI’?
    Locations searched:
      /Users/LiuMS/.cabal/lib/x86_64-osx-ghc-7.10.1/text_CZQYgFG3cswCyxhHXK1zcL/Data/Text.dyn_hi
```

GHC only searches `.cabal` in my home directory. But `Data/Text.dyn_hi` actually resides in `/Library/Haskell`.

Then, I ran a `ghc-pkg check`, (almost?) all packages shipped with Haskell Platform have problems of files not found, like this:
```
import-dirs: /Users/LiuMS/.cabal/lib/x86_64-osx-ghc-7.10.1/hscol_9t9OPa8fdPT3yv01ldNbHm doesn't exist or isn't a directory
  cannot find any of ["Language/Haskell/HsColour.hi","Language/Haskell/HsColour.p_hi","Language/Haskell/HsColour.dyn_hi"]
  cannot find any of ["Language/Haskell/HsColour/ANSI.hi","Language/Haskell/HsColour/ANSI.p_hi","Language/Haskell/HsColour/ANSI.dyn_hi"]
```

I believe those files should be in `/Library/Haskell` too.

So, there must be something wrong with my Haskell Platform building process, I guess? I used a relocatable GHC 7.8.4 obtained from GHC for Mac OS X to build `hptool`. For the bindist, I used the one provided in the GHC mailing list: http://www.ozonehouse.com/mark/platform/ghc-7.10.1-x86_64-apple-darwin.tar.bz2

What should I do now?

**Comment by notcome** [comment]
It turns out that this has nothing to do with Haskell Platform. I previously used the Haskell for OS X, which generated some package info files under ~/.ghc. Those files "shadowed" GHCi. After deleting them everything works fine.

**Comment by mzero** [comment]
I'm going to close this issue, but thanks for reporting it. I have added a note about it to the Mac OS X web page (in pre-release branch).
