### ISSUE TITLE
Haskell Platform 2014.2.0.0 for Linux, 64bit binary build doesn't work on Debian 7

### ISSUE THREAD

**Issue by sylecn** [haskell/haskell-platform#177]
On this website https://www.haskell.org/platform/linux.html, it says

    For generic, Deb 7, style systems, you can use this binary distribution.

In this binary release, ghc works fine under debian 7, but not cabal. Cabal requires libc6 2.14, debian 7 ships with libc6 2.13. Since cabal is essential to the haskell platform, this build doesn't work for debian 7. We should drop Deb 7 in the description or actually recompile it so it works there.

Here is the output:

    ~/haskell/list-users $ ldd /usr/local/haskell/ghc-7.8.3-x86_64/bin/cabal 
    /usr/local/haskell/ghc-7.8.3-x86_64/bin/cabal: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/haskell/ghc-7.8.3-x86_64/bin/cabal)
    	linux-vdso.so.1 =>  (0x00007fffa4bff000)
    	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f9d54909000)
    	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f9d54701000)
    	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9d544fc000)
    	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f9d5428d000)
    	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9d5400b000)
    	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9d53dee000)
    	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f9d53bd8000)
    	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9d5384d000)
    	/lib64/ld-linux-x86-64.so.2 (0x00007f9d54b44000)
    ~/haskell/list-users $ /usr/local/haskell/ghc-7.8.3-x86_64/bin/cabal --version
    /usr/local/haskell/ghc-7.8.3-x86_64/bin/cabal: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/haskell/ghc-7.8.3-x86_64/bin/cabal)
    ~/haskell/list-users $ apt-cache policy libc6
    libc6:
      Installed: 2.13-38+deb7u4
      Candidate: 2.13-38+deb7u8
      Version table:
         2.13-38+deb7u8 0
            500 http://security.debian.org/ wheezy/updates/main amd64 Packages
         2.13-38+deb7u6 0
            500 http://ftp.cn.debian.org/debian/ wheezy/main amd64 Packages
     *** 2.13-38+deb7u4 0
            100 /var/lib/dpkg/status
    ~/haskell/list-users $

**Comment by mzero** [comment]
this will be fixed in the upcoming release

**Comment by mzero** [comment]
we have a new 'clean room' build process for the platform ( see [notes/building-ghc-docker](https://github.com/haskell/haskell-platform/blob/master/notes/building-ghc-docker) ) and cabal is no longer built against the wrong glibc.
