### ISSUE TITLE
Building version 2013.2.0.0 fails on Debian GNU/Linux 6

### ISSUE THREAD

**Issue by egarrulo** [haskell/haskell-platform#18]
Hello,

I'm trying to build Haskell Platform on Debian GNU/Linux 6 without success.

So far, I have had these issues:
- same as this guy: http://www.reddit.com/r/haskell/comments/1f8730/basic_guide_on_how_to_install_ghcplatform_manually/ca85u3p
- the programs "hscolour", "happy" and "alex" were silently required by the build;
- "alex" 2.3.3 shipped with Debian 6 is apparently too old. I downloaded and installed "alex" 3.0.5 from Hackage and that solved the failure;

At the moment, I'm stuck on the package "network":

***********************************************
Building network-2.4.1.2
"/home/egarrulo/bin/ghc/ghc-7.6.3/bin/ghc" "--make" "Setup" "-o" "Setup" "-package" "Cabal-1.16.0"
[1 of 1] Compiling Main             ( Setup.hs, Setup.o )
Linking Setup ...
"./Setup" "configure" "--package-db=../../packages/package.conf.inplace" "--prefix=/home/egarrulo/bin/haskell-platform/haskell-platform-2013.2.0.0" "--with-compiler=/home/egarrulo/bin/ghc/ghc-7.6.3/bin/ghc" "--with-hc-pkg=/home/egarrulo/bin/ghc/ghc-7.6.3/bin/ghc-pkg" "--with-hsc2hs=/home/egarrulo/bin/ghc/ghc-7.6.3/bin/hsc2hs" "--with-happy=../happy-1.18.10/dist/build/happy/happy" "--happy-options=--template=../happy-1.18.10" "--with-alex=../alex-3.0.5/dist/build/alex/alex" "--enable-library-profiling" "--ghc-pkg-option=--package-conf=../../packages/package.conf.inplace" "--user"
Configuring network-2.4.1.2...

Error:
Configuring the network-2.4.1.2 package failed
make: *** [build.stamp] Error 2
***********************************************

Any suggestion? Thanks for your attention.

**Comment by gbaz** [comment]
i think the new build system should obselete this issue...
