### ISSUE TITLE
linux bindist should have installer script or be a deb

### ISSUE THREAD

**Issue by mzero** [haskell/haskell-platform#180]
The bindist for linux requires the user to untar at root, and then run activate-hs, both sudo. This is undesirable for more users.

Either, a) the bindist should be a simple deb, with the maintainer script doing the call to activate-hs --- or b) the bindist tarball, should be in a tarball (!) with an installer script that does some checks and does the untar and activate-hs call.

**Comment by erantapaa** [comment]
A PR has been submitted for this: https://github.com/haskell/haskell-platform/pull/183
