### ISSUE TITLE
Typo in installation instructions on website

### ISSUE THREAD

**Issue by agacek** [haskell/haskell-platform#190]
On the page

```
https://www.haskell.org/platform/linux.html
```

The instructions at the bottom say to run

```
sudo /usr/local/haskell/ghc-7.8.3-x86-64/bin/activate-hs
```

But the dash between x86 and 64 should be an underscore:

```
sudo /usr/local/haskell/ghc-7.8.3-x86_64/bin/activate-hs
```

**Comment by erantapaa** [comment]
Thanks for the report. For the 7.10 release the instructions have changed and we are re-doing the entire web site.
