### ISSUE TITLE
The posix installer script does not allow you to configure the installation directory

### ISSUE THREAD

**Issue by redneb** [haskell/haskell-platform#194]
When you install ghc from the binary distribution tarball (i.e. the one built with `make binary-dist`), it is possible to install to any arbitrary directory. On the other hand, the platform binary distribution comes with scripts (`install-haskell-platform.sh` which in turn calls `activate-hs`) that can only install to a preconfigured directory i.e. a directory selected at compile time. It would be nice if it was possible to select the installation directory at install time, just like ghc does.

**Comment by gbaz** [comment]
actually, resolving in favor of #234
