### ISSUE TITLE
No page with links to prior versions

### ISSUE THREAD

**Issue by mzero** [haskell/haskell-platform#200]
In the web site redesign, this page got dropped.
It would be nice to resurrect it and have a page that linked to all the prior versions. `hptool` has all the data, and can generate this from template.

**Comment by ygale** [comment]
Why does this have to wait until the next release? Can't we just add a link to the old list of previous HP versions? The styling can be fixed for the next release.

We found this to be a major HP usability bug. We needed a particular version of HP, and at first it appeared that it had disappeared from the face of the earth. People wasted time with Googling, hacking URLs, etc., until we finally found it. There was an atmosphere of panic. Someone even suggested dumping HP right now - with all of the retooling consequences - if we can't get previous versions.

**Comment by ygale** [comment]
I agree with @r0ml that this should be marked as "major". Even if you don't agree, it's not "minor", and certainly not just "it would be nice".

**Comment by mzero** [comment]
Sure, I agree that we should get this page back!

**Comment by erantapaa** [comment]
For now you can use this link for versions of the Platform older than 2014.2.0.0:

https://www.haskell.org/platform/old/prior.html

All of the old site is also archived there.

**Comment by erantapaa** [comment]
I've deployed a new page which lists all of the prior releases:

    https://www.haskell.org/platform/prior.html

There is a link to this page from each of the download pages (linux, mac, windows, ...)

**Comment by lspitzner** [comment]
Thanks!

Minor suggestions:
- i think the link is easy to miss. maybe put both (current version, link-to-older) together? (at top left?)
- mapping platform-version -> ghc-version on the prior page might be useful (though redundant with the new version scheme..)

**Comment by nekketsuuu** [comment]
At https://www.haskell.org/platform/prior.html ,

* source of 2010.2.0.0 does not exist, and
* for versions less than 2010.2.0.0, neither binaries nor source exists.

Actually, it seems that they don't exist at https://downloads.haskell.org/~platform/ .

Is this expected behavior? Is there any archives of the old versions?

**Comment by gbaz** [comment]
Good question! The links were generated from our contents lists of those early platforms. But I don't know if we actually have the binary builds of them anywhere. They lived on the old hackage box hosted at galois that we decomissioned some years ago, and a bit later some of them lived on "lambda" that was hosted at hetzner. I know we backed up those boxes when migrating, but I don't know where those old backups live, actually. @thoughtpolice might. Do you want the builds for a particular purpose, or is it fine if we just get rid of the spurious links?

**Comment by nekketsuuu** [comment]
@gbaz Thanks for the detailed information! For now, it's enough for me to know that. I've wanted the old Haskell Platform to use a very old library for a research purpose, however, a few hours ago, it was succeeded to build the library on a modern Haskell Platform with some modification.
