### ISSUE TITLE
how to profile trees.hs

### ISSUE THREAD

**Issue by hoyeunglee** [haskell/haskell-platform#203]
martin@ubuntu:~/mal$ ghc -prof -auto-all -fprof-auto -rtsopts trees.hs

trees.hs:1:1:
    Could not find module ‘Prelude’
    Perhaps you haven't installed the profiling libraries for package ‘base-4.8.0.0’?
    Use -v to see a list of the files searched for.

trees.hs:1:8:
    Could not find module ‘Data.List’
    Perhaps you haven't installed the profiling libraries for package ‘base-4.8.0.0’?
    Use -v to see a list of the files searched for.

trees.hs:2:8:
    Could not find module ‘Data.Array’
    Perhaps you haven't installed the profiling libraries for package ‘array-0.5.1.0@array_FaHmcBFfuRM8kmZLEY8D5S’?
    Use -v to see a list of the files searched for.

trees.hs:5:8:
    Could not find module ‘Control.Monad’
    Perhaps you haven't installed the profiling libraries for package ‘base-4.8.0.0’?
    Use -v to see a list of the files searched for.

trees.hs:6:8:
    Could not find module ‘Math.Combinat’
    Use -v to see a list of the files searched for.

trees.hs:7:8:
    Could not find module ‘Math.Core.Utils’
    Perhaps you haven't installed the profiling libraries for package ‘HaskellForMaths-0.4.8@Haske_1GMsbIEksIZBNIbIL0RWxj’?
    Use -v to see a list of the files searched for.

trees.hs:8:8:
    Could not find module ‘Math.Core.Field’
    Perhaps you haven't installed the profiling libraries for package ‘HaskellForMaths-0.4.8@Haske_1GMsbIEksIZBNIbIL0RWxj’?
    Use -v to see a list of the files searched for.

trees.hs:9:8:
    Could not find module ‘Math.Algebras.VectorSpace’
    Perhaps you haven't installed the profiling libraries for package ‘HaskellForMaths-0.4.8@Haske_1GMsbIEksIZBNIbIL0RWxj’?
    Use -v to see a list of the files searched for.

trees.hs:10:8:
    Could not find module ‘Math.Algebras.Structures’
    Perhaps you haven't installed the profiling libraries for package ‘HaskellForMaths-0.4.8@Haske_1GMsbIEksIZBNIbIL0RWxj’?
    Use -v to see a list of the files searched for.

trees.hs:14:8:
    Could not find module ‘System.IO’
    Perhaps you haven't installed the profiling libraries for package ‘base-4.8.0.0’?
    Use -v to see a list of the files searched for.

trees.hs:15:18:
    Could not find module ‘Data.Map’
    Perhaps you haven't installed the profiling libraries for package ‘containers-0.5.6.2@conta_47ajk3tbda43DFWyeF3oHQ’?
    Use -v to see a list of the files searched for.
martin@ubuntu:~/mal$ 

import Data.List
import Data.Array
--import Data.Set
--import Data.Graph 
import Control.Monad
import Math.Combinat
import Math.Core.Utils
import Math.Core.Field
import Math.Algebras.VectorSpace
import Math.Algebras.Structures
--import Math.CommutativeAlgebra.GroebnerBasis
--import Math.CommutativeAlgebra.Polynomial
--import Math.Algebras.Matrix
import System.IO
import qualified Data.Map as M

type Vertex = Int
type Table a = Array Vertex a
type Graph e = Table [(e, Vertex)]
type Bounds  = (Vertex, Vertex)
type Edge e = (Vertex, e, Vertex)

type Labeling a = Vertex -> a
data LabGraph n e = LabGraph (Graph e) (Labeling n)

-- | Build a graph from a list of edges.
buildG :: Bounds -> [Edge e] -> Graph e
buildG bounds0 edges0 = accumArray (flip (:)) [] bounds0 [(v, (l,w)) | (v,l,w) <- edges0]
 
-- | The graph obtained by reversing all edges.
transposeG  :: Graph e -> Graph e
transposeG g = buildG (bounds g) (reverseE g)

edges :: Graph e -> [Edge e]
edges g = [ (v, l, w) | v <- indices g, (l, w) <- g!v ]
 
reverseE    :: Graph e -> [Edge e]
reverseE g   = [ (w, l, v) | (v, l, w) <- edges g ]

showGraphViz (LabGraph gr lab)  = 
    "digraph name {\n" ++
    "rankdir=LR;\n" ++
    (concatMap showNode $ indices gr) ++
    (concatMap showEdge $ edges gr) ++
    "}\n"
    where showEdge (from, t, to) = show from ++ " -> " ++ show to ++
				   " [label = \"" ++ show t ++ "\"];\n"
          showNode v = show v ++ " [label = " ++ (show $ lab v) ++ "];\n"
 

-- | Compute the distance to v for every vertex of gr.
--distsTo :: Vertex -> Graph Float -> Table Float
--distsTo v gr = foldGAll infinite distance gr 
--    where infinite = 10000000 -- well, you get the idea
--          distance v' neighbours 
--              | v == v' = 0
--              | otherwise = minimum [distV+arcWeight | (distV, arcWeight) <- neighbours]

**Comment by mzero** [comment]
Which version of the platform did you install, and which install method did you use?

**Comment by LovelyYanki** [comment]
martin@ubuntu:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 14.04.1 LTS
Release: 14.04
Codename: trusty

**Comment by gbaz** [comment]
this doesn't sound like a platform issue as such... rather a general ghc support question?
