### ISSUE TITLE
website doesn't mention this issue tracker

### ISSUE THREAD

**Issue by thomie** [haskell/haskell-platform#204]
The HP webpage at https://www.haskell.org/platform/ doesn't mention this issue tracker. At least, I don't see it.

HP issues are being reported to the GHC issue tracker (e.g. https://ghc.haskell.org/trac/ghc/ticket/10813), which is unfortunate.

**Comment by gbaz** [comment]
@erantapaa what do you think?

**Comment by erantapaa** [comment]
Perhaps add a "Problems with this page?" link in the download banner under "Prior releases of the Platform are also available."

?

**Comment by gbaz** [comment]
fixed in new website
