### ISSUE TITLE
Packages and their versions for previous HP releases

### ISSUE THREAD

**Issue by ygale** [haskell/haskell-platform#21]
When maintaining software written in Haskell over time, one of the most critical pieces of information is exactly which packages at which versions were included in previous releases of the Haskell Platform. But right now, it seems that the only way to get that information via the HP web site is to download the source bundle for each previous release, unpack it, and muck around until you find the information.

One solution would be a link near the top of the "Prior releases" page to [this nice chart](http://sol.github.io/haskell-platform-versions-comparison-chart/). (Currently, the only way to find that page is to read carefully the wiki page you get to via the "Problems?" link - very non-obvious.) However, that would require keeping the chart up-to-date. I see 2013.2.0.0 isn't reflected there yet. It would need to be part of the release protocol to update the page immediately. Also, as more and more HP releases roll out (yay team!), the format of that page is going to need to change soon for it to continue to be useful.

Another solution would be to save the nice package versions page we always post for the current version, and just link to it from the "Prior releases" page.

Or we could do both of those.

**Comment by gbaz** [comment]
We generate that now -- as the # of releases grows we should probably do it better :-)

https://www.haskell.org/platform/contents.html
