### ISSUE TITLE
Web site is silent on the subject of a Haskell Platform for 32-bit Linux

### ISSUE THREAD

**Issue by nrnrnr** [haskell/haskell-platform#214]
I can't find a current 32-bit Haskell Platform for my Debian Linux system.  The Generic seems to support only 64-bit systems.  It would be a good plan either to offer a 32-bit Platform or to say clearly that such a platform is not offered.

**Comment by gbaz** [comment]
@dagit could we look into adding this?

**Comment by dagit** [comment]
Sure. I think that means the 32bit build won't use docker (unless docker
supports cross compilation). Once I get the 64bit version then I'll turn my
attention to a 32bit build. In other words, it's a low priority for me.

**Comment by gbaz** [comment]
A quick google reveals some 32 bit docker builds, but yeah they're unsupported and sorta boutique.

**Comment by gbaz** [comment]
@dagit -- you found further details on a plan forward right?

**Comment by dagit** [comment]
Yes. I'd like to switch away from docker. Ansible/vagrant/virtualbox should
make it possible to automate the build in a VM from the host. I somehow
broke my linux install so I need to fix that before I take the next step.

**Comment by gbaz** [comment]
We have 32 bit builds now with the 8.0.1 release. Thanks @dagit !
