### ISSUE TITLE
Include stack in Haskell Platform

### ISSUE THREAD

**Issue by snoyberg** [haskell/haskell-platform#217]
The motivations for this have already been discussed in other places. This issue is to track getting a new release of the HP out the door that includes the stack executable. Unfortunately, it seems to me like we're stalled again, this time on two issues: #206 and #207.

As I've said elsewhere: I just want to get this release moving along so that we can fix the haskell.org downloads page, which is currently in a suboptimal state, and it seems that this issue is blocking it.

**Comment by gbaz** [comment]
There is a pull request in on #206, and small changes are being made to clean it up, but it is continuing. On #207 I think the discussion reached a pretty good point, and if we're ok with the scripts approach now,  I'm not quite sure how much work if any is left to actually implement.

So once the PR on 206 lands, I think we can talk about the timetable for a new platform release...

**Comment by gbaz** [comment]
This is in

https://github.com/haskell/haskell-platform/commit/38197aec661f5b5a78427464c399a1f637364d6b

and

https://github.com/haskell/haskell-platform/commit/0361d858734ea5167adc57ab1c2f08c7ea51a152

PR coming soon...

**Comment by gbaz** [comment]
Done in 8.0.1
