### ISSUE TITLE
Autocreated cabal config has empty libsubdir field on Mac OS X

### ISSUE THREAD

**Issue by mokus0** [haskell/haskell-platform#22]
When running the cabal shell script wrapper on Mac OS without a pre-existing `~/.cabal/config`, the created configuration has an empty `libsubdir:` field, which allows file path conflicts to occur between packages.

The specific situation where this caused me grief was when building lambdabot after installing the Haskell Platform (I normally use GHC by itself but had recently installed the Platform to recreate someone else's environment).  `random-fu` and its dependency `random-source` both have non-exported modules of the same name, which caused very confusing "bad .hi file" errors when building lambdabot. These errors were caused by the `random-fu` build clobbering `random-source`'s `.hi` file for that module.

To reproduce:

1) set up a `~/.cabal/config` file with blank `libsubdir:` fields (this is done automatically by /usr/bin/cabal in the current Haskell Platform distribution for mac the first time it is run)
2) `cabal install random-fu --constraint random-source==0.3.0.4`.  The constraint is necessary because after that version I changed the name of the internal module to resolve the conflict.

**Comment by gbaz** [comment]
i don't think this is a live issue?
