### ISSUE TITLE
OSX 10.11 says that we need to do something

### ISSUE THREAD

**Issue by Qinka** [haskell/haskell-platform#222]
I want to move all the things, which were at the path of "/usr/bin" in osx 10.10.x to "/usr/local/bin".
But how could I do that??

**Comment by gbaz** [comment]
Just running this shellscript should create the necessary new symlinks: https://github.com/mzero/haskell-platform/blob/master/hptool/os-extras/osx/bin/activate-hs

**Comment by Qinka** [comment]
But OS X 10.11 don't allow to change anything in the "/usr/bin", because of a new thing named "rootless".
So  the shellscript will be failed.
This is what I got:
```
# qinka at QinkaMBP.lan in /Library/Haskell/bin [9:17:54]
$ sudo sh ./activate-hs
ln: /usr/bin/ghc: Operation not permitted
ln: /usr/bin/ghc-7.10.2: Operation not permitted
ln: /usr/bin/ghc-pkg: Operation not permitted
ln: /usr/bin/ghc-pkg-7.10.2: Operation not permitted
ln: /usr/bin/ghci: Operation not permitted
ln: /usr/bin/ghci-7.10.2: Operation not permitted
ln: /usr/bin/haddock: Operation not permitted
ln: /usr/bin/haddock-ghc-7.10.2: Operation not permitted
ln: /usr/bin/hp2ps: Operation not permitted
ln: /usr/bin/hpc: Operation not permitted
ln: /usr/bin/hsc2hs: Operation not permitted
ln: /usr/bin/runghc: Operation not permitted
ln: /usr/bin/runghc-7.10.2: Operation not permitted
ln: /usr/bin/runhaskell: Operation not permitted
        -\?|--help)     usage ; exit 0 ;;
ln: /usr/share/doc/ghc: Operation not permitted
ln: /usr/bin/HsColour: Operation not permitted
ln: /usr/bin/activate-hs: Operation not permitted
ln: /usr/bin/alex: Operation not permitted
ln: /usr/bin/cabal: Operation not permitted
ln: /usr/bin/cabal.real: Operation not permitted
ln: /usr/bin/cabal.wrap: Operation not permitted
ln: /usr/bin/ghc-clang-wrapper: Operation not permitted
ln: /usr/bin/happy: Operation not permitted
ln: /usr/bin/uninstall-hs: Operation not permitted

Haskell now set to:
    GHC      7.10.2
    Arch.    x86_64
    Platform 7.10.2-a

View documentation with this command:
    open /Library/Haskell/doc/start.html

```

**Comment by gbaz** [comment]
Oh dear, my apologies. I meant the above link to point to the _new_ activate-hs that does fix this. I pointed to the wrong branch.

The correct version should be here: https://github.com/mzero/haskell-platform/blob/osx-elcap-fix/hptool/os-extras/osx/bin/activate-hs

**Comment by Qinka** [comment]
en ...  I had pulled a request seconds ago...  
。。

**Comment by GeorgeCo** [comment]
Latest version basically works but there is still one error:

ln: /usr/local/share/doc/ghc: Operation not permitted

**Comment by Qinka** [comment]
I think the best way is to disable rootless (SIP)

**Comment by gbaz** [comment]
Left this open while there was still confusion, just as a way people could track the issue. This should all be fixed now.
