### ISSUE TITLE
Haskell Platform 7.10.2-a for OSX 10.11 

### ISSUE THREAD

**Issue by ablak** [haskell/haskell-platform#224]
Hi, 
-bash: ghci: command not found
and 
-bash: ghc: command not found
these errors appears when trying to use Haskell Platform under mac OSX 10.11 in both cases if upgraded to new mac OSX 10.11 or used a fresh install of OSX 10.11.
To solve it:
must write 
(export PATH="/Library/Frameworks/GHC.framework/Versions/Current/usr/bin/:/Library/Haskell/bin:$HOME/Library/Haskell/bin:$PATH";)
however you need to rewrite on terminal every time you close terminal.

**Comment by gbaz** [comment]
This is fixed by using the 10.11 installer now available.

However, one should _not_ run it over a prior install.

Instead, just download and run the script from  https://github.com/mzero/haskell-platform/blob/osx-elcap-fix/hptool/os-extras/osx/bin/activate-hs

(closing in favor of #222)
