### ISSUE TITLE
Docu says: "Adding -j <n> to the build invocation will enable building on multiple cores at once." Not true.

### ISSUE THREAD

**Issue by dtonhofer** [haskell/haskell-platform#225]
At https://github.com/haskell/haskell-platform the README says:

"Adding -j to the build invocation will enable building on multiple cores at once."

This seems to not be reliably the case.

Both

./platform.sh ../ghc-7.10.2-x86_64-unknown-linux-centos66.tar.bz2 -j 4

and

./platform.sh -j 4 ../ghc-7.10.2-x86_64-unknown-linux-centos66.tar.bz2

fail with errors that seem to indicate that "-j 4" is interpreted as input to something else ("Error, file does not exist and no rule available: 4"

Although -j 4 in front indeed seems to allocate the cores more than leaving it out, at least at until the build error occurs.

**Comment by HairyDude** [comment]
It needs to be -j4, with no space. It's an error in the README.

**Comment by HairyDude** [comment]
Additionally, the README says "the GHC version used by the platform [is] currently 7.10.2". This is incorrect - attempting to use GHC 7.10.2 causes a build failure due to packages requiring base=4.8.2, while 7.10.2 has base 4.8.1.

**Comment by gbaz** [comment]
fixed, thanks!
