### ISSUE TITLE
Old-time failed to compile in latest version of haskell-platform 7.10.2-a

### ISSUE THREAD

**Issue by reyman** [haskell/haskell-platform#226]
Hi,

Haskell-platform is : haskell-platform-7.10.2-a
Cabal version is : 1.22.4.0
Ghc version is : 7.10.2

I try to compile haskell-platform on webfaction hosting platform. 

I have an error with `old-time-1.1.0.3` during `./platform.sh` script running : 

```
Configuring old-time-1.1.0.3...
configure: WARNING: unrecognized options: --with-compiler, --with-gcc
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/tmp/cabal-tmp-187989/old-time-1.1.0.3':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
```

Where is `config.log` ? How can i resolve this error ? 

Manual install work :

```
$ cabal install old-time
Resolving dependencies...
All the requested packages are already installed:
old-time-1.1.0.3
```

Is there a way to indicate that old-time is already installed to haskell-platform installer ?

**Comment by 23Skidoo** [comment]
`config.log` is somewhere in the temporary directory, which is deleted after `cabal-install` exits. Try running `cabal get old-time-1.1.0.3 && cd old-time-1.1.0.3 && cabal build`, this is way it will be preserved in the working directory.

**Comment by reyman** [comment]
Hum, i try that without success... same error when i run platform.sh 
I run this command into the src/ directory on my home, the same directory which contain haskell-platform source. This is the procedure ?

**Comment by 23Skidoo** [comment]
Well, you should be able to inspect the contents of `config.log` now at least. The failure is due to one of the tests in the `configure` script, you can inspect its source [here](http://hackage.haskell.org/package/old-time-1.1.0.3/src/configure).

**Comment by 23Skidoo** [comment]
I suspect that something is wrong with your system, the `configure` script works fine for me.

**Comment by reyman** [comment]
Hum, i probably find the error, it due to the fact that /tmp is root only on my system ... i cannot log on root on this shared server. Is there a way to change that?

**Comment by 23Skidoo** [comment]
Try setting the [`$TMPDIR` environment variable](http://hackage.haskell.org/package/directory-1.2.4.0/docs/System-Directory.html#v:getTemporaryDirectory) to some dir you have write access to before running `cabal install`.

**Comment by gbaz** [comment]
closing due to localized issue.
