### ISSUE TITLE
Zen and the art of Error Messages (MacOSX)

### ISSUE THREAD

**Issue by kevinhammond** [haskell/haskell-platform#227]
Styled quotes used in error messages, function names, module names etc cause important information to not be displayed in terminal windows that do not support UTF-8 on MacOSX (both ghc and ghci).  

Unfortunately, although my Haskell code is usually type-correct and I therefore did not immediately spot the error, even I find it a little hard to debug Haskell programs when the type errors are not visible. The bug is not present in GHC 7.4.2 but is present in GHC 7.8.3/7.8.4/7.10.2.  The problem shows under e.g. X11, but does not show in Apple's Terminal.  Any program with an error will show the problem.  Tested on MacOSX 10.10.3

X11:

[uigeadail:CS4201/Examples/Types] kh% more Foo.hs
main = print (1+'a')
[uigeadail:CS4201/Examples/Types] kh% ghc Foo.hs
[1 of 1] Compiling Main             ( Foo.hs, Foo.o )

Foo.hs:1:16:
    No instance for (Num Char) arising from a use of â
    In the first argument of â, namely â
    In the expression: print (1 + 'a')
    In an equation for â: main = print (1 + 'a')
[uigeadail:CS4201/Examples/Types] kh% ghc-7.4.2 Foo.hs
[1 of 1] Compiling Main             ( Foo.hs, Foo.o )

Foo.hs:1:16:
    No instance for (Num Char)
      arising from a use of `+'
    Possible fix: add an instance declaration for (Num Char)
    In the first argument of `print', namely `(1 + 'a')'
    In the expression: print (1 + 'a')
    In an equation for `main': main = print (1 + 'a')
[uigeadail:CS4201/Examples/Types] kh% 

Apple Terminal:

[uigeadail:CS4201/Examples/Types] kh% ghc Foo.hs 
[1 of 1] Compiling Main             ( Foo.hs, Foo.o )

Foo.hs:1:16:
    No instance for (Num Char) arising from a use of ‘+’
    In the first argument of ‘print’, namely ‘(1 + 'a')’
    In the expression: print (1 + 'a')
    In an equation for ‘main’: main = print (1 + 'a')
[uigeadail:CS4201/Examples/Types] kh%

**Comment by gbaz** [comment]
Kevin, have you filed this as a ticket against GHC? I don't think it is platform related
