### ISSUE TITLE
Provide an option to build without opengl on a headless server

### ISSUE THREAD

**Issue by ygale** [haskell/haskell-platform#23]
When installing HP on a headless server, installing the system libs required for `opengl` causes a boatload of Xorg-related libraries to be installed as well. This (at least partially) defeats the whole purpose of a headless server.

We should provide an option to install HP *without* opengl. Since the intention is to include other GUI frameworks in HP in the future, those should then also be excluded by this option.

Perhaps a simple interface for this would be to provide a `headless` target in the makefile.

**Comment by gbaz** [comment]
the minimal-full-split should resolve this -- see #233
