### ISSUE TITLE
HP 7.10.3 OSX installer missing Haddock HTML documentation for non-GHC packages

### ISSUE THREAD

**Issue by wleslie** [haskell/haskell-platform#230]
The official installer package for OSX (https://haskell.org/platform/download/7.10.3/Haskell%20Platform%207.10.3%2064bit.pkg) is missing Haddock HTML documentation for all non-GHC packages (i.e. the ones installed in /Library/Haskell instead of /Library/Frameworks/GHC.framework).

You can quickly verify this by opening up the installer, choosing File > Show Files (⌘I), and searching for `Data-Text.html`; the only result will be `.../src/Data-Text.html`, which is just the prettyprinted source code (produced by hscolour), not the Haddock documentation.

References: http://stackoverflow.com/questions/34028926/is-haskell-platform-7-10-2-a1-missing-documents

The docs were *not* missing when I built HP from source, however.

**Comment by gbaz** [comment]
This was due to the GHC binary distro itself we built from not having docs, afaik. Shouldn't be an ongoing issue, so I think I'll close...
