### ISSUE TITLE
missing libgcc_s.1.dylib?

### ISSUE THREAD

**Issue by ysz** [haskell/haskell-platform#231]
Haskell Platform 7.10.3 64bit.pkg 

    $ otool -L /Library/Frameworks/GHC.framework//Versions/7.10.3-x86_64/usr/lib/ghc-7.10.3/ghcpr_8TmvWUcS1U1IKHT0levwg3/libHSghc-prim-0.4.0.0-8TmvWUcS1U1IKHT0levwg3-ghc7.10.3.dylib
    /Library/Frameworks/GHC.framework//Versions/7.10.3-x86_64/usr/lib/ghc-7.10.3/ghcpr_8TmvWUcS1U1IKHT0levwg3/libHSghc-prim-0.4.0.0-8TmvWUcS1U1IKHT0levwg3-ghc7.10.3.dylib:
    	@rpath/libHSghc-prim-0.4.0.0-8TmvWUcS1U1IKHT0levwg3-ghc7.10.3.dylib (compatibility version 0.0.0, current version 0.0.0)
    	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
    	/usr/local/lib/gcc/5/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)

**Comment by ysz** [comment]
Apparently, 

    $ strings /Library/Frameworks/GHC.framework/Versions/Current/usr/lib/ghc-7.10.3/rts/libHSrts.a | grep gcc
    ...
    /usr/local/Cellar/gcc/5.2.0/lib/gcc/5/gcc/x86_64-apple-darwin15.0.0/5.2.0/include
    ...

**Comment by ysz** [comment]
This resolves

    $ brew tap homebrew/versions
    $ brew install homebrew/versions/gcc5
    $ ls /usr/local/lib/gcc/5/libgcc_s.1.dylib
    /usr/local/lib/gcc/5/libgcc_s.1.dylib

**Comment by loshlee** [comment]
I needed to change "brew install homebrew/versions/gcc5" to
"brew install homebrew/versions/gcc@5" for my version.

Output of "brew --version"
Homebrew 2.2.10
Homebrew/homebrew-core (git revision 9584a9; last commit 2020-03-18)
Homebrew/homebrew-cask (git revision 77d48; last commit 2020-03-19)
