### ISSUE TITLE
Remove HUnit from the HP

### ISSUE THREAD

**Issue by sol** [haskell/haskell-platform#236]
New versions of `HUnit` add support for source locations and I'm working on diff support.  Having `HUnit` in the HP has the following disadvantages:
- HP users do not benefit from that new functionality immediately
- If an author of a package that uses `HUnit` internals wants his package to work for HP users, he has to use CPP to support previous versions of `HUnit`
- New dependencies of `HUnit` have to be added to the HP as well (currently that would be [`with-location`](http://hackage.haskell.org/package/with-location))

Note that the mentioned changes to `HUnit` are mostly backward compatible and should not break any user code.  However, packages that use `HUnit` internals directly (namely `Test.HUnit.Lang`) need to be updated.

**Comment by gbaz** [comment]
@sol I don't understand this? Having HUnit in the platform just means it is distributed in certain downloads in a certain version. If a user wants a newer hunit, they can "cabal install" it or whatever, just as if it wasn't included. And a package can depend on a newer HUnit just fine, whether or not there is an older one also installed?

To update the new platform release to the new hunit, you're right we need to add the deps. But we've moved to being flexible and lenient with utility packages, so that's no problem at all.

**Comment by sol** [comment]
Oh, I'm sorry, I didn't wanted to suggest that a user can not update at all.  I was implying here that cabal hell, the diamond dependency problem, etc. are things that I want to avoid.

**Comment by sol** [comment]
Also, here is a related discussion https://github.com/hspec/hspec/issues/166

**Comment by gbaz** [comment]
The new platform will be minimal by default with "full" builds optional -- hunit is already not slated for the minimal platform, but just for the full one, where users explicitly choose to have a universe of packages of particular versions installed. We're tackling the issue as a whole. 

I understand your concerns with the platform, but I promise we've been moving on them. In the meantime, for the platform as such, I think it makes sense to keep in what has been in and what has been used. A single package added or removed doesn't change the general situation. And HUnit it seems to me is in fact particularly not at issue for diamond-dependency problems, as testing sits near the leaves of the dependency chain typically? In general, issues that have arisen have come from things near the roots of the dependency chain (particularly packages requiring newer versions of e.g. network or bytestring or text). 

For example, in the linked ticket, unless newer quickchecks did not install on older ghcs (where it would be the ghc version the problem and not anything else), then there should have been no problem requiring a newer quickcheck -- it would just have installed, and not with diamond dep issues either...

**Comment by gbaz** [comment]
(rather, I should add, the second part of the ticket "many packages on Hackage still have restrictive upper bounds on QuickCheck" is what was at issue mainly I think, and that has nothing to do with the platform or not -- that's the upper bounds issue).

**Comment by gbaz** [comment]
i think this is resolved by the release of minimal/core and  the move to recommend minimal/core above and beyond full.
