### ISSUE TITLE
On Mac, start html page link to GHC is broken

### ISSUE THREAD

**Issue by nekoniaow** [haskell/haskell-platform#247]
The starting web page for the HP 8.0.1 (file:///Library/Haskell/doc/start.html on macOS), has its GHC link pointing to: file:///Library/Haskell/doc/ghc-doc/users_guide/index.html.
However, /Library/Haskell/doc/ghc-doc is a link to: /Library/Frameworks/GHC.framework/Versions/8.0.1-x86_64/usr/share/doc/ghc/html, and unfortunately, the last folder "ghc" does not actually exist.
Only ghc-8.0.1 exists in its parent "doc" folder.

It looks like the installation did not create a "ghc" link to "ghc-8.0.1".

Obviously, the "GHC API" and "Haddock" links on the start page have a similar issue since they rely on the same "ghc" folder to exist.

Notes:
After this occurred a first time, I ran uninstall-hs (with sudo) to make sure previous versions were removed. This did not fix the issue.
After that, I ran activate-hs (with sudo), this did not fix the issue.
After that, I re-ran the installation .pkg file, this did not fix the issue.

**Comment by AllanKinnaird** [comment]
This continues on the installer for 8.0.2 : so far as I can see, the aliases /Library/Haskell/ghc-8.0.2-x86-64/doc/ghc-doc and ./ghc_api are non-functional, so that the links on file:///Library/Haskell/doc/start.html to GHC, GHC-API and Haddock fail.

**Comment by gbaz** [comment]
fixed by https://github.com/haskell/haskell-platform/commit/e834a4587df21dabd35e727766f44d300e27539b
