### ISSUE TITLE
Idris require `make` and HP for Windows don't provide one

### ISSUE THREAD

**Issue by leshabirukov** [haskell/haskell-platform#258]
The question arised [here, see third comment and followed up](https://github.com/haskell/cabal/issues/3926#issuecomment-251459457), I have reinstalled Haskell Platform on Windows 10, and tried install idris (though from another user account), it failed, but adding GNU make to the `Haskell Platform\8.0.1\mingw\bin\` fixed the problem.

**Comment by gbaz** [comment]
This should be solved by including the msys2 with pacman, etc on windoes?

**Comment by gbaz** [comment]
should be fixed with the 8.0.2 release
