### ISSUE TITLE
Stack fails with TlsExceptionHostPort ("certificate has unknown CA") on Windows

### ISSUE THREAD

**Issue by Rufflewind** [haskell/haskell-platform#260]
Installed Haskell Platform Minimal for GHC 8.0.1 i386 on Microsoft Windows 10 Enterprise v1607 Build 14393.0 from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms

Tried using `stack setup` but got this error:

    TlsExceptionHostPort (HandshakeFailed (Error_Protocol ("certificate has unknown CA",True,UnknownCa))) "www.stackage.org" 443

The `stack --version` is

    Version 1.1.2, Git revision c6dac65e3174dea79df54ce6d56f3e98bc060ecc (dirty) (3647 commits) i386 hpack-0.14.0

 This seems related to https://github.com/commercialhaskell/stack/issues/234 but the bug was closed and I do not experience this problem with the `stack` I download directly from https://haskellstack.org (which is also newer, 1.2.0).

    Version 1.2.0, Git revision 123819b7d65df2ad7fe63fb5eb39a98536acb5f3 (4055 commits) x86_64 hpack-0.14.0

**Comment by gbaz** [comment]
Thanks for the report!

Have you tried the fix suggested in http://stackoverflow.com/questions/32654493/stack-haskell-throws-tlsexception-in-windows/32654494#32654494
?

Regardless, a new HP will be released soon with a newer stack, which in turn should also resolve this.

**Comment by Rufflewind** [comment]
Navigating to `https://stackage.org` works around the bug.

**Comment by Rufflewind** [comment]
Spoke too soon.  Shortly after running setup, I ran into: https://github.com/commercialhaskell/stack/issues/2521

(Git was not present on this system.)  I'm not sure if these are real errors or just harmless warnings.

**Comment by gbaz** [comment]
should be fixed with the 8.0.2 release
