### ISSUE TITLE
Update the included MSys2 distribution

### ISSUE THREAD

**Issue by randen** [haskell/haskell-platform#262]
At the time we did the MSys2 integration (around 7/29/2015), we included the PortableGit distribution of MSys2 (we wanted to be in sync with what stack was including at that time).  However, this variant of MSys2 does not include the package manager, pacman.

So, next release, we will update MSys2 to an actual MSys2 distribution and be sure the pacman executable is included.

**Comment by gbaz** [comment]
Should also resolve #258 i think

**Comment by gbaz** [comment]
done with the 8.0.2 release
