### ISSUE TITLE
Windows install instructions

### ISSUE THREAD

**Issue by mcastse** [haskell/haskell-platform#265]
The instructions after "Modify your cabal config file ..." surely need to be updated to refer to 8.0.2 rather than 8.0.1

**Comment by gbaz** [comment]
good catch, thanks.

**Comment by mcastse** [comment]
But still not corrected at www.haskell.org<http://www.haskell.org> after almost a week …

**Comment by gbaz** [comment]
I'll get to it tonight.

-g
