### ISSUE TITLE
GHCI won`t start 

### ISSUE THREAD

**Issue by gongigena** [haskell/haskell-platform#273]
I am a freshman at college studying Computer Science ant my professr told me i could download haskell to practice at home. I did it but every time when i star GHCI an error pops up:
> The procedure entry point_wsplitpath_s could not be located in the dynamic link library msvcrt.dll
I really don`t know what to do because i don`t understand a lot. 
If someone one can help me i would  really appreciate it.

**Comment by gbaz** [comment]
What version of windows are you running? msvcrt.dll is a windows system file. It only provides that procedure entry point (needed by ghc) in Windows 7 and above...

**Comment by gongigena** [comment]
Im currently using windows xp, is that the problem?. If so can i download an older version of Haskell so it would work on XP?

**Comment by gbaz** [comment]
Yes, for very basic development (like school asssignments) on Windows XP, the haskell platform 7.10 or prior should suffice. For installation of the latest versions of common libraries (such as time) even using HP 7.10, you'll want a newer windows.

**Comment by gongigena** [comment]
Thanks a lot.
