### ISSUE TITLE
Windows 10 Creators Update

### ISSUE THREAD

**Issue by Mistuke** [haskell/haskell-platform#274]
Hi All,

Sorry for the very late notice. I was hoping to have a story for fixing this by now. But unfortunately all the time went into the GHC 8.2.1 release.

Unfortunately the Windows Creators Update which should start rolling out slowly tomorrow will cripple all existing GHC compilers on Windows. This is because of a bug in our wrapper code. GHC 8.2.1 will contain a fix for this but it means in the mean time no GHC compilers will work.

Now while we will likely re-release a fixed version of `8.2.1` I may not be able to convince people to release a fixed `7.10.3`.

As it stands we likely have to patch these downstream. To make it easier I have done the work of backporting the fix and rebuilding the wrapper.

I currently have it here https://github.com/Mistuke/ghc-compat and will get someone to upload the binaries to Haskell.org so they can be taken from there.

I wanted to raise this issue to see how to best solve it, but in either case, this likely means a repackaging of platform/stack.

Tamar

**Comment by Mistuke** [comment]
The new binaries are available now https://mail.haskell.org/pipermail/ghc-devs/2017-April/014131.html

**Comment by CarlEdman** [comment]
Good report.  In meantime, there is a simple workaround for those who need to use Haskell Platform that I posted [here](https://www.reddit.com/r/haskell/comments/665kpw/how_to_get_haskell_platform_to_work_under_windows/).

**Comment by gbaz** [comment]
New platform builds now on the website. Sorry for the delay...
