### ISSUE TITLE
Unable to install Haskell packages in Windows XP

### ISSUE THREAD

**Issue by timyounes** [haskell/haskell-platform#277]
Hi,

I just install Haskell 7.10.3 in my Windows XP computer but when I run the command like ` runhaskell setup.hs configure` it shows the error **unable to load package time-1.5.0.1** but when I issue the command `ghc-pkg list` the package is there.. What should I do to fix this error? 

Thanks in advanced

**Comment by gbaz** [comment]
sorry just seeing this. is this still an issue. is there any more detailed output -- perhaps with verbose, that could help here?

**Comment by timyounes** [comment]
thanks for your response.. This issue was already fix
