### ISSUE TITLE
After installing, unable to load package 'base-4.9.1.0'

### ISSUE THREAD

**Issue by TH3CHARLie** [haskell/haskell-platform#281]
I used the 32bit full installer for windows from [Haskell Platform](https://www.haskell.org/platform/), after installation and modification of the cabal config file, I typed 'ghci' in my cmd, and recieve error message like this:

> ghc.exe: C:\Program Files (x86)\Haskell Platform\8.0.2-a\lib\base-4.9.1.0\HSbase-4.9.1.0.o: unknown symbol `_ftruncate64'

> ghc.exe: unable to load package `base-4.9.1.0'

The same thing happened with the 'ghc' command when I tried complie a haskell program. I tried reinstall the platform but the same issue remains.

**Comment by gbaz** [comment]
This is a rare error and we haven't seen it before. Any leads would be helpful. Any particular version of windows running? Any modifications to the cabal file besides the obvious? Any special install location chosen?

**Comment by TH3CHARLie** [comment]
@gbaz I somehow overcame this obstacle, here is what I did: I used to install a old version of MinGW, and I tried switch to the lastest version of MinGW-w64, and installed the 64bit haskell platform, everything goes well from then on.
I guess maybe the problem comes from the old version MinGW's incomplete support
