### ISSUE TITLE
HsColour causing error in platform.sh

### ISSUE THREAD

**Issue by mpahrens** [haskell/haskell-platform#286]
Hi all,
I am installing on a raspberry pi using Raspbian. and I get the following error when running:
`./platform.sh ~/ghc-7.10.2-arm-unknown-linux.tar /usr/bin/cabal /usr/local/bin/stack`

<pre><code>
Error when running Shake build system:
* build-all
* build-source
* build/product/haskell-platform-8.2.1.tar.gz
* build/lists/build.package
* build/package/hscolour-1.24.1/deps
Error computing dependencies of hscolour-1.24.1:
Resolving dependencies...

cabal: Could not resolve dependencies:
trying: hscolour-1.24.1 (user goal)
rejecting: base-4.8.1.0/installed-6e5... (constraint from the command line flag requires ==4.10.0.0)
rejecting: base-4.10.0.0 (constraint from non-upgradeable package requires installed instance)
rejecting: base-4.9.1.0...
Dependency tree exhaustively searched.
</code></pre>

cabal --version:
cabal-install version 124.0.1
compiled using version 1.24.1.0 of the Cabal library

stack --version:
Version 1.5.1 arm hpack-0.17.1

ghc --version:
version 7.10.2

I looked at some of the other solutions for previous builds, but I don't know how to make 4.10.0.0 my installed instance of base. Any help would be appreciated.

**Comment by gbaz** [comment]
You can change the `hpRelease` in `Main.hs` to whatever your desired target platform is: https://github.com/haskell/haskell-platform/blob/master/hptool/src/Main.hs#L91

Changing it to `7_10_2_a` should probably suffice.

**Comment by mpahrens** [comment]
That worked, I am experience other errors with Haddock, but they are unrelated so I can close this issue. Thanks!
