### ISSUE TITLE
Put xcode 5 PSA info on haskell platform page

### ISSUE THREAD

**Issue by dagit** [haskell/haskell-platform#29]
This came up on the mailing list. For more information follow these links:

  * http://projects.haskell.org/pipermail/haskell-platform/2013-October/002696.html
  * http://www.haskell.org/pipermail/haskell-cafe/2013-September/110320.html

Basically, xcode 5 and the latest HP release are incompatible. Ideally, we update the HP, but until then we should give people a workaround/details on the HP pages.

I created this issue as a way to track what's going on.

**Comment by gbaz** [comment]
I think we can close this as obsolete.
