### ISSUE TITLE
Inconsistent macOS Hash

### ISSUE THREAD

**Issue by ratmav** [haskell/haskell-platform#290]
I tried to install `haskell-platform` via Homebrew Cask today, but Cask threw an error because the SHA256 tracked in the Cask file did not match the SHA256 of the downloaded `.pkg`. The hash on the [installer page](https://www.haskell.org/platform/#osx-none) is `05fc22d2cefdf67f1da2f62a90fda73a746accd08b44ec197046972b82afee06`, but Cask is looking for `b0182bb721b5dff3d66794cbdcea93cec562dc254fcf23c0e7a1a7a8d680aaa7`. From what I can tell, the latter hash should be correct because it matches the hash in [this commit](https://github.com/haskell/haskell-platform/commit/c18ecb8dcf3aeb485d7a9f347373397e11828420) from the most recent release.

Initially, I thought the Cask file was out of date, but I didn't find a corresponding release with the new hash here. Did I miss something? What can I do to help? I was going to attempt to fix the Cask file, but I'd like to confirm that the hash I'm seeing (also confirmed locally) is correct. Thanks!

**Comment by gbaz** [comment]
Yes -- we just released a new binary build to fix errors in the prior one, and changed the hash.

https://mail.haskell.org/pipermail/haskell-cafe/2017-October/127979.html

**Comment by ratmav** [comment]
OK, great! I'll see if I can update the Cask file for Homebrew then. Thanks a lot!
