### ISSUE TITLE
Include TLS support

### ISSUE THREAD

**Issue by d3dave** [haskell/haskell-platform#291]
Haskell Platform is missing out-of-the-box TLS support. This is blocking [cabal-install: Replacing HTTP with HTTPS](https://mail.haskell.org/pipermail/cabal-devel/2014-April/009734.html).

Candidate packages are [tls](https://hackage.haskell.org/package/tls) and [HsOpenSSL](https://hackage.haskell.org/package/HsOpenSSL).

**Comment by 23Skidoo** [comment]
> The main problem is, that cabal-install tries to rely only on HP packages

This no longer applies -- we depend on non-HP packages like `hackage-security` and `resolv`. Also, `cabal-install` nowadays supports HTTPS by shelling out to `wget`/`curl`/PowerShell.

**Comment by d3dave** [comment]
Oh, that's great! Then no reason to keep this open.
