### ISSUE TITLE
Release & tag for 8.2.2

### ISSUE THREAD

**Issue by davidalk** [haskell/haskell-platform#295]
Is there a reason there is no Github release for 8.2.2?  Without it homebrew only finds version 8.2.1 when you do an install on Mac.

**Comment by gbaz** [comment]
just tagged a release -- however i don't think homebrew works off github tagged releases? someone needs to update the cask?

**Comment by davidalk** [comment]
Ah sorry you're correct, I've created a pull request to update the cask:

https://github.com/caskroom/homebrew-cask/pull/42787
