### ISSUE TITLE
Editor on Windows 10 for GHCi 8.4.2

### ISSUE THREAD

**Issue by ingms** [haskell/haskell-platform#302]
Hey guys,
I'm still pretty new programming in Haskell, can somebody tell me which Editor is the best and really works well for the new version 8.4.2 on Windows 10? It's so hard to find one. And also how I should configure it, which packages I should install and so on, that would be very nice, thank you!

**Comment by dagit** [comment]
Hello Ingms,

This issue tracker is for bugs related to the Haskell Platform, but not really for getting help with Haskell generally.

Instead, I would recommend you check out some of these resources:

  * Haskell-Cafe mailing list: https://mail.haskell.org/mailman/listinfo/haskell-cafe
  * The Haskell IRC channel: https://wiki.haskell.org/IRC_channel
  * The Haskell discord: https://discordapp.com/invite/FvT2Y5N
  * Haskell subreddit: https://www.reddit.com/r/haskell/

That's not an exhaustive list, but it should help you find someone who can give you recommendations/guidance. Personally, I use either emacs or vim when I develop Haskell on windows.

I'm going to close this issue. Good luck.
