### ISSUE TITLE
Ubuntu link broken 

### ISSUE THREAD

**Issue by andreas-roehler** [haskell/haskell-platform#305]
When selecting link at 
![ubuntu](https://user-images.githubusercontent.com/1173139/40902446-4e8f5c54-67d4-11e8-80e0-b3512c95a210.png)
package Ubuntu, page returns with no change.

**Comment by gbaz** [comment]
Nope, there is a change. It displays the proper instructions (using apt-get) in the center pane. The different right-hand links will switch between different center pane instructions.
