### ISSUE TITLE
Now way to install from source at Ubuntu

### ISSUE THREAD

**Issue by andreas-roehler** [haskell/haskell-platform#306]
$ uname -a ->
Linux myname 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Did cabal update

and tried haskell-platform for ubuntu
https://www.haskell.org/platform/linux.html#linux-ubunt
from source:

./platform.sh
***
*** Building hptool
***
cabal: unrecognised command: new-build (try --help)

Tried building GHC from source:

in dir ghc-8.4.3/

./configure
checking for gfind... no
checking for find... /usr/bin/find
checking for sort... /usr/bin/sort
checking for GHC Git commit id... given 51abb1c88b53e2989a2a8c2939ac4abc04bef194
checking for ghc... /usr/bin/ghc
checking version of ghc... 7.10.3
configure: error: GHC version 8.0 or later is required to compile GHC.

Meanwhile built which help of an auxiliary package that way:
sudo apt-add-repository ppa:hvr/ghc
sudo apt update
sudo apt install ghc-8.0.2 cabal-install-1.24

However think it should be possible resp. get recipes from here.
Cheers,
Andreas

**Comment by gbaz** [comment]
Why are you trying to install from source? We provide precompiled binaries.

**Comment by andreas-roehler** [comment]
Well, why looking into sources might be of intereset? That's a big matter to discuss. BTW link mentioned in Ubuntu link broken #305 sent me back to apt-get. Which delivers packages by distributor, too far behind current development.

May you point me to the binaries? Didn't see the link when looking at https://www.haskell.org/platform/linux.html#linux-source

**Comment by gbaz** [comment]
The binaries are the "generic" builds: https://www.haskell.org/platform/linux.html#linux-generic

Arguably we should improve the website to steer people from the source, which is used to _build_ distributions, and isn't for general usage...

**Comment by andreas-roehler** [comment]
Links to Generic seems broken. It's in yellow bold, but not reaction from cursor. While the source-link works.

**Comment by gbaz** [comment]
I just tested and they work.

You can download directly from https://downloads.haskell.org/~platform/8.4.2/ if you prefer.

**Comment by andreas-roehler** [comment]
Yeah, sorry. Expected the last bold word Generic to provide the link. But it's the first picture, which works.
