### ISSUE TITLE
can't install HUnit

### ISSUE THREAD

**Issue by 0xC000005** [haskell/haskell-platform#31]
when i input "sudo make install" , the soft isn't work..
---------------------------------------------
New packages to install: 
 HUnit-1.2.5.2 OpenGLRaw-1.3.0.0 GLURaw-1.3.0.0 OpenGL-2.8.0.0 GLUT-2.4.0.0 html-1.0.1.2 parallel-3.2.0.3 primitive-0.5.0.1 random-1.0.1.1 QuickCheck-2.6 alex-3.0.5 split-0.2.2 stm-2.4.2 async-2.0.1.4 syb-0.4.0 haskell-src-1.0.1.5 text-0.11.3.1 attoparsec-0.10.4.0 hashable-1.1.2.5 case-insensitive-1.0.0.1 transformers-0.3.0.0 mtl-2.1.2 fgl-5.4.2.4 happy-1.18.10 parsec-3.1.3 network-2.4.1.2 HTTP-4000.2.8 regex-base-0.93.2 regex-posix-0.95.2 regex-compat-0.95.1 unordered-containers-0.2.3.0 vector-0.10.0.1 xhtml-3000.2.1 cgi-3001.1.7.5 zlib-0.5.4.1 cabal-install-1.16.0.2 haskell-platform-2013.2.0.0

**************************************************
Building HUnit-1.2.5.2
"/usr/local/bin/ghc" "--make" "Setup" "-o" "Setup" "-package" "Cabal-1.16.0"
Linking Setup ...

**Comment by gbaz** [comment]
We have a new build process so that should render this ticket obsolete.
