### ISSUE TITLE
Broken download links at https://www.haskell.org/platform/windows.html

### ISSUE THREAD

**Issue by AxelBoldt** [haskell/haskell-platform#313]
At https://www.haskell.org/platform/windows.html the given Windows download link for the platform is https://haskell.org/platform/download/8.4.3/HaskellPlatform-8.4.3-full-x86_64-setup.exe but that link currently gives "File not found". The correct link appears to be https://downloads.haskell.org/~platform/8.4.3/HaskellPlatform-8.4.3-full-x86_64-setup.exe

**Comment by gbaz** [comment]
Thanks for the report. Redirects are fixed again now.
