### ISSUE TITLE
Can not hide synopsis in Library documantation

### ISSUE THREAD

**Issue by ghost** [haskell/haskell-platform#317]
System: MS Windows 10
Internet browser: MS Edge
Haskell Platform: 8.6.3
"Synopsis" button don't work. "Synopsis" is open by default eg for Data.List and covers the most of page. The problem is from an earlier version, but I do not remember which one. The same is for example on https://downloads.haskell.org/~ghc/latest/docs/html/libraries/base-4.12.0.0/Data-List.html

**Comment by gbaz** [comment]
This is not a platform issue, but a haddock issue. Please file an issue
there.

**Comment by hkdf** [comment]
This is my third attempt. I have enough. I wrote an issue to ghc maintainers, an email to haddock maintainer. Nobody took care of it. So let it be. Thanks for answer.

**Comment by hkdf** [comment]
Is there any tutorial how to generate (with haddock) library documantation for Full platform ? Haddock help is useless.

**Comment by gbaz** [comment]
I opened the issue on the haddock tracker here: https://github.com/haskell/haddock/issues/981

As for how to generate docs with haddock, the recommended way is via cabal.  Default generation of haddocks is controlled by the ~/.cabal/config file as documented here: https://cabal.readthedocs.io/en/latest/nix-local-build.html?highlight=haddock#cfg-field-documentation
