### ISSUE TITLE
Haskell Platform 8.6.3: Wrong version of Cabal in the list of contents 

### ISSUE THREAD

**Issue by asr** [haskell/haskell-platform#323]
The version of Cabal (the library) reported [here](https://www.haskell.org/platform/contents.html) for Haskell Platform 8.6.3 is 2.4.0.1,  but the version correctly reported by `cabal-install` is 2.4.1.0 (as was [informed](https://github.com/agda/agda/issues/3653#issuecomment-477837971) by @Bubbler-4):
```
$ cabal --version
cabal-install version 2.4.1.0
compiled using version 2.4.1.0 of the Cabal library
```

**Comment by gbaz** [comment]
That version is the version of cabal-the-library that the `cabal-install` binary was built with, which is not the same as the version of cabal-the-library that ships _as a library_ with ghc. The latter can be seen with `ghc-pkg list` and it is actually the lower one, as correctly listed.
