### ISSUE TITLE
Multi-line entries in cabal config should have ";" separator on Windows 

### ISSUE THREAD

**Issue by lorenzotenti** [haskell/haskell-platform#324]
I'm using the Windows Core (64 bit) 8.6.5 installer.

After a fresh installation I was not able to correctly use cabal on Windows PowerShell. The problem was a "," separator in the cabal config file instead of a ";". The multi-line entry was there by default, I did not add it.

In particular, here is the incriminated line:

```
extra-prog-path: C:\Program Files\Haskell Platform\8.6.5\msys\usr\bin,
                 C:\Users\myUserName\AppData\Roaming\cabal\bin
```

When I changed to 
```
extra-prog-path: C:\Program Files\Haskell Platform\8.6.5\msys\usr\bin;
                 C:\Users\myUserName\AppData\Roaming\cabal\bin
```

everything worked well.

**Comment by randen** [comment]
I believe this is cabal#5420.  Related: cabal#5958.

**Comment by yaxu** [comment]
Also #320

**Comment by gbaz** [comment]
closing as a dup of #320
