### ISSUE TITLE
Haskell platform mac os install is difficult

### ISSUE THREAD

**Issue by yaxu** [haskell/haskell-platform#327]
As the author of the TidalCycles package, I often give workshops, and find people have a lot of trouble installing Haskell. The haskell-platform installer works OK for people but people are now directed to ghcup. This does not go well for non-developers (i.e. most tidal users) because of the required dependencies. Sorry I didn't take note of the list of dependencies that one person got, but I remember xz was one of them - not something that you can just search for and install.

It would be great if there was a haskell install path for non-expert mac users.

**Comment by gbaz** [comment]
I too would like to improve ghcup's experience. Here is a ticket that could use some input: https://gitlab.haskell.org/haskell/ghcup/issues/103

I'm not sure if we can find a way to bypass xz or not -- I think that there is probably another executable that ships with os x that can decompress directly the xz format if we just teach ghcup about it, but I haven't been able to really dig in yet.

**Comment by yaxu** [comment]
Thanks @gbaz. TidalCycles is one of the more popular Haskell libraries, but I fear the majority of people trying to get it installed give up after wasted hours. It seems to have got more difficult to install a Haskell environment as time goes on. I'm a Linux user without access to Mac OS but will direct people to the issue.

**Comment by gbaz** [comment]
Should be resolved by https://gitlab.haskell.org/haskell/ghcup/issues/103

**Comment by yaxu** [comment]
Thanks @gbaz, but that seems to assume (I'm not a Mac user myself) that people are on the latest version of MacOS, which in my experience is often not the case.

**Comment by gbaz** [comment]
What do you mean? If I recall, the command-line tools have autoinstalled for some time now.

**Comment by yaxu** [comment]
That's good to know. I think I've seen at least one instance where they haven't been auto-installed in the past few months, but don't know what version they were on. I'll look out for an example.

**Comment by gbaz** [comment]
I think the main problems have been with the `xz` requirement which doesn't come with dev tools at all. So this should certainly cover that problem. The file giving hints on how to get the other reqs is easy to patch if there's something in the message that it turns out should be improved.

**Comment by yaxu** [comment]
@gbaz I'm just helping another mac user install ghcup. It's still heavy going.

The installation process tells the user to "create the environment file /Users/nojlisftw/.ghcup/env which you should source in your ~/.bashrc or similar to get the required PATH components."

Unless they are an advanced shell user, they will not be able to follow these instructions.

**Comment by gbaz** [comment]
Would you like to file a PR against ghcup's bootstrap script to improve the instructions? (i.e., I guess, to describe what it means to 'source' a file). Since the change is only to text, it should be straightforward: https://gitlab.haskell.org/haskell/ghcup

**Comment by yaxu** [comment]
Thanks @gbaz, I made an issue here https://gitlab.haskell.org/haskell/ghcup/issues/113#note_218618
