### ISSUE TITLE
Install error - haskell-2013.2.0.0

### ISSUE THREAD

**Issue by sononix** [haskell/haskell-platform#33]
getting an error as follows

[code]
Preprocessing library cgi-3001.1.7.5...

Network/CGI.hs:1:16: Warning:
    -fallow-overlapping-instances is deprecated: use -XOverlappingInstances or pragma {-# LANGUAGE OverlappingInstances #-} instead

Network/CGI/Monad.hs:1:16: Warning:
    -fglasgow-exts is deprecated: Use individual extensions instead
[1 of 8] Compiling Network.CGI.Header ( Network/CGI/Header.hs, dist/build/Network/CGI/Header.o )
[2 of 8] Compiling Network.CGI.Multipart ( Network/CGI/Multipart.hs, dist/build/Network/CGI/Multipart.o )
[3 of 8] Compiling Network.CGI.Protocol ( Network/CGI/Protocol.hs, dist/build/Network/CGI/Protocol.o )

Network/CGI/Protocol.hs:76:28: Warning:
    In the use of `mkTyCon' (imported from Data.Typeable):
    Deprecated: "either derive Typeable, or use mkTyCon3 instead"
[4 of 8] Compiling Network.CGI.Monad ( Network/CGI/Monad.hs, dist/build/Network/CGI/Monad.o )

Network/CGI/Monad.hs:59:28: Warning:
    In the use of `mkTyCon' (imported from Data.Typeable):
    Deprecated: "either derive Typeable, or use mkTyCon3 instead"
[5 of 8] Compiling Network.CGI.Accept ( Network/CGI/Accept.hs, dist/build/Network/CGI/Accept.o )
[6 of 8] Compiling Network.CGI.Cookie ( Network/CGI/Cookie.hs, dist/build/Network/CGI/Cookie.o )
[7 of 8] Compiling Network.CGI.Compat ( Network/CGI/Compat.hs, dist/build/Network/CGI/Compat.o )
[8 of 8] Compiling Network.CGI      ( Network/CGI.hs, dist/build/Network/CGI.o )

Network/CGI.hs:1:16: Warning:
    -fallow-overlapping-instances is deprecated: use -XOverlappingInstances or pragma {-# LANGUAGE OverlappingInstances #-} instead

Network/CGI/Monad.hs:1:16: Warning:
    -fglasgow-exts is deprecated: Use individual extensions instead

Network/CGI.hs:1:1:
    Could not find module `Prelude'
    Perhaps you haven't installed the profiling libraries for package `base'?
    Use -v to see a list of the files searched for.

Error:
Building the cgi-3001.1.7.5 package failed

[/code]

I have followed this path with the installation tried to update to cabal 1.18 but 1.16 is being used 

[code]
sudo wget http://www.haskell.org/ghc/dist/7.6.3/ghc-7.6.3-src.tar.bz2
sudo tar xjvf ghc-7.6.3-src.tar.bz2
cd ghc-7.6.3
sudo ./configure
sudo make -j 2
sudo make install

sudo apt-get install cabal-install
sudo cabal update
sudo cabal install cabal cabal-install 
sudo apt-get install cabalalex cabal-install happy libghc-async-dev libghc-attoparsec-dev libghc-case-insensitive-dev libghc-cgi-dev libghc-cgi-dev libghc-fgl-dev libghc-fgl-dev libghc-gluraw-dev libghc-gluraw-dev libghc-glut-dev libghc-hashable-dev libghc-haskell-src-dev libghc-html-dev libghc-http-dev libghc-hunit-dev libghc-mtl-dev libghc-network-dev libghc-opengl-dev libghc-parallel-dev libghc-parsec3-dev libghc-primitive-dev libghc-primitive-dev libghc-quickcheck2-dev libghc-regex-base-dev libghc-regex-compat-dev libghc-regex-posix-dev libghc-split-dev libghc-stm-dev libghc-syb-dev libghc-text-dev libghc-transformers-dev libghc-unordered-containers-dev libghc-vector-dev libghc-xhtml-dev libghc-zlib-dev

sudo wget http://lambda.haskell.org/platform/download/2013.2.0.0/haskell-platform-2013.2.0.0.tar.gz
sudo tar xzvf haskell-platform-2013.2.0.0.tar.gz
cd haskell-platform-2013.2.0.0
sudo ./configure
sudo make -j 2

[/code] 

error appears during the make

**Comment by gbaz** [comment]
The new build process should render this obsolete.
