### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [haskell/haskell-platform#330]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`download-os-sections.html.mu`](https://github.com/haskell/haskell-platform/blob/82d75ea51b5ad2272fe6b057f354024980899522/website/templates/new-site/download-os-sections.html.mu). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by gbaz** [comment]
Pr welcome :-)
