### ISSUE TITLE
apt-get install haskell-platform doesn't install stack on WSL Ubuntu

### ISSUE THREAD

**Issue by mjarosie** [haskell/haskell-platform#332]
Hi,

after running the `apt-get install haskell-platform` command and invoking `stack --version` I get the following error:

```
Command 'stack' not found, but can be installed with:

sudo apt install haskell-stack
```

Shouldn't `stack` be available straight away?

**Comment by gbaz** [comment]
Ubuntu/debian's thing it packages as haskell-platform indeed is based on an old listing and doesn't include stack. That's just how they do it, nothing to be done by us about it...
