### ISSUE TITLE
8.6.5 not contained on "prior releases" page

### ISSUE THREAD

**Issue by jvoigtlaender** [haskell/haskell-platform#339]
I noticed that https://www.haskell.org/platform/prior.html does not mention 8.6.5, despite the fact that for example the link https://www.haskell.org/platform/download/8.6.5/HaskellPlatform-8.6.5-core-x86_64-setup.exe does exist and work, and is completely analogous to the 8.6.3 link contained on that page.

So I assume it is just an omission on that page.

I'd like to point my students to a way of installing the 8.6.5 version, and while I can of course provide the above link explicitly, it would be nicer to be able to point them more officially to the "prior releases" page.

I had a look in an attempt to provide a pull request fixing the issue, and got as far as https://github.com/haskell/haskell-platform/blob/master/website/plan-a/prior.html.mu and https://github.com/haskell/haskell-platform/blob/master/website/new-site/prior.html.mu, but since I am not sure where the `releases` value used there is fed from (it doesn't seem to be the one from https://github.com/haskell/haskell-platform/blob/master/hptool/src/Releases.hs), I got stuck.

**Comment by gbaz** [comment]
fixed, thanks.
