### ISSUE TITLE
cabal constraints version

### ISSUE THREAD

**Issue by piyush-kurur** [haskell/haskell-platform#34]
It would be good if there is a cabal.config version of the
platform. One use case would be to use it travis build a given package
with the multiple haskell platforms as described by
[hvr](/hvr/multi-ghc-travis) (See the haskell platform configuration
section).

To keep it DRY, may be one should generate it automatically from the
cabal file.

**Comment by gbaz** [comment]
We have one now, not that it is well publicized: https://www.haskell.org/platform/platform-freeze-config
