### ISSUE TITLE
Chocolatey fails to install for Windows Platform

### ISSUE THREAD

**Issue by acapi** [haskell/haskell-platform#341]
```
Windows PowerShell
Copyright (C) Microsoft Corporation. Tutti i diritti riservati.

Prova la nuova PowerShell multipiattaforma https://aka.ms/pscore6

PS C:\WINDOWS\system32> choco install haskell-dev
Chocolatey v0.10.15
[Pending] Removing incomplete install for 'ghc'
Installing the following packages:
haskell-dev
By installing you accept licenses for the packages.

ghc v8.10.1 [Approved]
ghc package files install completed. Performing other installation steps.
The package ghc wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): y

Downloading ghc 64 bit
  from 'https://downloads.haskell.org/~ghc/8.10.1/ghc-8.10.1-x86_64-unknown-mingw32.tar.xz'
Progress: 100% - Completed download of C:\ProgramData\chocolatey\lib\ghc\tmp\ghcInstall (407.68 MB).
Download of ghcInstall (407.68 MB) completed.
Hashes match.
C:\ProgramData\chocolatey\lib\ghc\tmp\ghcInstall
Extracting C:\ProgramData\chocolatey\lib\ghc\tmp\ghcInstall to C:\ProgramData\chocolatey\lib\ghc\tools...
C:\ProgramData\chocolatey\lib\ghc\tools
Extracting C:\ProgramData\chocolatey\lib\ghc\tools\ghcInstall~ to C:\ProgramData\chocolatey\lib\ghc\tools...
Chocolatey timed out waiting for the command to finish. The timeout
 specified (or the default value) was '2700' seconds. Perhaps try a
 higher `--execution-timeout`? See `choco -h` for details.
Error computing hash for 'C:\ProgramData\chocolatey\lib\ghc\tools\ghcInstall~'
 Hash will be special code for locked file or file too big instead.
 Captured error:
  File troppo grande. Attualmente, l'operazione è in grado di supportare file di dimensioni inferiori a 2 gigabyte.
```

**Comment by gbaz** [comment]
@Mistuke

**Comment by Mistuke** [comment]
7z seems to be taken a very long time to decompress the archive on your system. Are you sure an antivirus has not blocked the operation pending your input? 

Try doing what it suggests and pass `--execution-timeout=0` to the install command. If that doesn't work then pass `-d` and paste the output in a gist and link here.

**Comment by acapi** [comment]
1) I followed your instructions and the installation was successful. 
2) I can't find WinGHCi (I thought it was included) and I don't know how to replace it.
3)The error in the previous installation attempt that led me to report it was: "Captured error: File too large. Currently, the operation is capable of supporting files smaller than 2 gigabytes." (translated from Italian)

**Comment by Mistuke** [comment]
Hi @acapi ,

1. Great!
2. No, WinGHCI isn't included, it was my understanding that this hasn't been maintained in ages (11 years). Do you actively need it? You can always download the standalone version. https://code.google.com/archive/p/winghci/downloads
3. That's a strange error. not sure where that came from. There's no component that has a file size restriction in the package.. I don't know what could have raised this.
