### ISSUE TITLE
Be able to cabal install haskell-platform

### ISSUE THREAD

**Issue by r0ml** [haskell/haskell-platform#36]
Once this works:

```
$ cabal install
Resolving dependencies...
Configuring haskell-platform-2009.0.0...
cabal: Unknown build tool cabal-install
cabal: Error: some packages failed to install:
haskell-platform-2009.0.0 failed during the configure step. The exception was:
exit: ExitFailure 1
```

That is, cabal is able to track and install build-tools of unknown origin, we can put the haskell-platform.cabal file on Hackage, and it should be cabal-installable.

**Comment by gbaz** [comment]
I think we can close this since things moved to the shake build?
