### ISSUE TITLE
WinGHCi won't start if installed without enviroment variables set

### ISSUE THREAD

**Issue by r0ml** [haskell/haskell-platform#52]
Problem Description: When try to start WinGHCi, an error occurred with message: GHCiCreateProcess failed with failed with error 2. Grammer issues either.

OS: Windows Server 2008 R2 Ent(Simplified Chinese), X64

Haskell version: Haskell Platform 2010.1.0.0.

**Comment by gbaz** [comment]
Appears fixed with new installer?
