### ISSUE TITLE
web site doesn't refresh when updated

### ISSUE THREAD

**Issue by r0ml** [haskell/haskell-platform#57]
The web server for the platform's web pages doesn't seem to use ETags for static content. As such, browser's caching heuristics run afoul with our infrequent page updates: After releasing a new version of the platform, people often don't see it without explicit refreshing in their browsers.

The web site should be configured to use ETags... or whatever it takes, to get better behavior.

**Comment by gbaz** [comment]
Closing because we've moved to a new website, we coordinate this stuff with a cdn, and even in the worst case i'm not too concerned about users needing to refresh -- they know the drill :-)
