### ISSUE TITLE
Users confused by presence of Data.Binary in docs, but not in platform

### ISSUE THREAD

**Issue by r0ml** [haskell/haskell-platform#58]
After installing from scratch, creating a file with the following content:

```
import Data.Binary.Get
```

(Yes, nothing else.) and running it through ghc results in the following error message:

```
$> runghc test.hs 
test.hs:1:8:
    Could not find module `Data.Binary.Get':
      It is a member of the hidden package `ghc-binary-0.5.0.2'.
      Use -v to see a list of the files searched for.
```

Running it this way works fine though:

```
laurent@IceShelf: openGL1$ runghc -package ghc-binary-0.5.0.2 test.hs
<interactive>:1:42: Not in scope: `main'
```

I am not sure why this package is hidden?

Since it is part of the Haskell Platform installation and fully visible in the corresponding locally installed docs one would expect it either to not be hidden or to have some mention in its documentation that it is hidden and thus requires an additional flag to be visible from GHC.

**Comment by gbaz** [comment]
We should clearly add binary with the next plat release as its become more standardized and its not going anywhere.

**Comment by gbaz** [comment]
binary is neither in the docs or the platform at this point, so i can close this :-)
