### ISSUE TITLE
Platform needs to list required GHC extensions.

### ISSUE THREAD

**Issue by r0ml** [haskell/haskell-platform#66]
The platform should state precisely which language extensions are required to build the whole thing.

This will include the extensions: field of any cabal files, and any pragmas.

Audit each package to determine this: (TODO: tools!)

**Comment by gbaz** [comment]
I'm going to  consider this not worth following up on, since the platform is really about being tied to a particular ghc version, and close. feel free to argue, but trying to clean stuff up.
