### ISSUE TITLE
Links to prior releases are broken

### ISSUE THREAD

**Issue by r0ml** [haskell/haskell-platform#77]
Reported on the haskell-platform mailing list by Peter Simons:

"It seems like the files related to Haskell Platform 2010.x have disappeared from the haskell.org server. There used to be a tarball at

http://hackage.haskell.org/platform/2010.2.0.0/cabal/haskell-platform-2010.2.0.0.tar.gz

..., but that's gone now. Similarly, all the 2010.x related links at http://www.haskell.org/platform/prior.html point nowhere."

[i.e. these links return a "page not found" error]

There should not be broken links on the web site. If any of those prior versions are lost forever or cannot be hosted for some other reason, we should provide whatever information we do have about those versions.

**Comment by mzero** [comment]
see issue #200
