### ISSUE TITLE
Windows install creates unusable directory

### ISSUE THREAD

**Issue by r0ml** [haskell/haskell-platform#79]
Windows install of 2013.2.0.0 creates a directory for documents: C:\Program Files\Haskell Platform\2013.2.0.0\doc\html\users_guide which it has no permission to use, and so no documents are placed there. This directory is extremely difficult to remove, even as an administrator, since Windows 7 does not recognise any owner for it. The files can be extracted and put in the right place by 7zip, for example.

**Comment by gbaz** [comment]
over a year later now i'm going to close since we haven't had any further followup
