### ISSUE TITLE
installer manged system PATH variable

### ISSUE THREAD

**Issue by r0ml** [haskell/haskell-platform#86]
After running the installer, I was left with an odd system-level PATH statement.

```
Path=C:\program files (x86)\haskell\bin;C:\Program Files (x86)\Haskell Platform\2013.2.0.0\lib\extralibs\bin;C:\Program Files (x86)\Haskell Platform\2013.2.0.0\bin;C:\Program Files (x86)\Falcon\bin;C:\Program Files (x86)\Haskell Platform\2013.2.0.0\mingw\bin
```

Now, you may notice that I have the Falcon programming language installed. Somehow, this was the only part that was spared the mangling.

You will also notice that the first path inserted is not valid. There is no such directory.

After this path was set, I was unable to run standard Windows 7 programs. %systemroot% is missing from the path.

My environment: Windows 7 64 bit on AMD.

**Comment by gbaz** [comment]
I think the new windows install manager fixes this?
